### ISSUE TITLE
Can't delete device Types

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#10]
Hi there,

Setup: MacTrack 4.0 (from git) and Cacti 1.0.3

I added a device type, then modified it and it shows it as a "new one" and I'm not able to delete  any of them. 

Everytime you create a new Site o device or SNMP options you never get a "save successful" message or whatever, just and empty page and then if you refresh the page it shows you what you have created.

![mtrack_devicetypes](https://cloud.githubusercontent.com/assets/13456559/23243619/eece6d7c-f9e4-11e6-81cf-89866c5a6ae5.png)

**Comment by cigamit** [comment]
Resolved, thanks!
