### ISSUE TITLE
Feature Request: Add ZyXEL Router

### ISSUE THREAD

**Issue by larieu** [Cacti/plugin_mactrack#100]
For USG series routers you can query via SNMP the mac address /IP  table as

smnpwalk ( -v 2c ) -c xxxxxxxx IPv4  .1.3.6.1.2.1.4.35.1.4.30.1.4

and the result is like this
.1.3.6.1.2.1.4.35.1.4.30.1.4.**192.168.68.122** = STRING: **00:01:02:03:04:05**
.1.3.6.1.2.1.4.35.1.4.30.1.4.**192.168.70.2** = STRING: **01:02:03:04:05:06**
.1.3.6.1.2.1.4.35.1.4.30.1.4.**192.168.74.7** = STRING: **02:03:04:05"06:07**
....

from this is easy to build the mac address / IP table 

according to
http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.2.1.4.35.1
it is a standard way to determine this

How to add this as a standard way to determine IP's for routers?

**Comment by cigamit** [comment]
Try using the standard collector.  Unless it's some custom cam and arp storage, it should just work.  If the arp table does not walk.  You can write a simple collector based upon others to walk the custom arp.

Once your collector is written, feel free to create a pull request to incorporate into the core.
