### ISSUE TITLE
Array to string conversion  

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#101]
2019/01/29 15:37:36 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[117]:clear_old_processes(), /plugins/mactrack/poller_mactrack.php[387]:db_execute_prepared())  
2019/01/29 15:37:36 - CMDPHP ERROR: A DB Exec Failed!, Error: Array to string conversion

**Comment by cigamit** [comment]
That one is fixed.  Thanks!
