### ISSUE TITLE
Parameter must be an array or an object that implements Countable 

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#102]
2019/01/29 15:34:17 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mactrack/mactrack_view_interfaces.php[38]:mactrack_view(), /plugins/mactrack/mactrack_view_interfaces.php[347]:mactrack_display_stats(), /plugins/mactrack/lib/mactrack_functions.php[2856]:sizeof(), CactiErrorHandler())  
2019/01/29 15:34:17 - ERROR PHP WARNING in Plugin 'mactrack': sizeof(): Parameter must be an array or an object that implements Countable in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/lib/mactrack_functions.php on line: 2856  
2019/01/29 15:34:13 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mactrack/mactrack_view_devices.php[38]:mactrack_view_devices(), /plugins/mactrack/mactrack_view_devices.php[352]:mactrack_display_stats(), /plugins/mactrack/lib/mactrack_functions.php[2856]:sizeof(), CactiErrorHandler())  
2019/01/29 15:34:13 - ERROR PHP WARNING in Plugin 'mactrack': sizeof(): Parameter must be an array or an object that implements Countable in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/lib/mactrack_functions.php on line: 2856  
2019/01/29 15:33:53 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mactrack/mactrack_view_devices.php[38]:mactrack_view_devices(), /plugins/mactrack/mactrack_view_devices.php[352]:mactrack_display_stats(), /plugins/mactrack/lib/mactrack_functions.php[2856]:sizeof(), CactiErrorHandler())  
2019/01/29 15:33:53 - ERROR PHP WARNING in Plugin 'mactrack': sizeof(): Parameter must be an array or an object that implements Countable in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/lib/mactrack_functions.php on line: 2856

**Comment by netniV** [comment]
This is a PHP 7.2 problem. You need to downgrade from PHP 7.2 to avoid the warnings because MacTrack hasn't been updated to deal with PHP 7.2 yet.

**Comment by jdcoats** [comment]
I backed down to 7.1 and this warning is gone but the errors reported in issue #103 still exist. Mactrack goes into a loop and never stops. Eventually will crash mysql. I can stop it by killing the mactrack processes and truncating mac_track_processes table. Mactrack doesnt really work at all for me right now.

**Comment by cigamit** [comment]
Closing this one.  Keep updating the other issue.
