### ISSUE TITLE
SQL Backtrace poller_mactrack.php, mactrack_scanner.php, mactrack_cisco.php, mactrack_functions.php

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#103]
![screen shot 01-30-19 at 09 16 am](https://user-images.githubusercontent.com/42470924/51987963-8d2dbc80-2471-11e9-9824-29bc43ff27f2.PNG)

**Comment by jdcoats** [comment]
The above is with todays commit d5e47ac

**Comment by jdcoats** [comment]
This is what it does when the poller starts
![screen shot 01-30-19 at 01 27 pm](https://user-images.githubusercontent.com/42470924/52003596-f5d96100-2492-11e9-925d-2ecdd5091aa8.PNG)

**Comment by jdcoats** [comment]
same issue with php 5.6, 7.1 & 7.2

**Comment by jdcoats** [comment]
I can no longer get mac's from my Nexus core switches, therefore no tracking is taking place.
[mactrack-no-macs.txt](https://github.com/Cacti/plugin_mactrack/files/2823298/mactrack-no-macs.txt)

**Comment by jdcoats** [comment]
I confirmed that arp oid's didnt change in functions and that they still produce the data but it is not getting into the tables. I did change the DEBUG message output by adding Nexus and run the debug again just to make sure that it runs that function. Don't know what else to try.
`lib/mactrack_functions.php 

} else {
                /* second attempt for Force10 Gear */
                $atifIndexes   = xform_stripped_oid('.1.3.6.1.2.1.4.22.1.1', $device);
                mactrack_debug('atifIndexes data collection complete Nexus');
                $atPhysAddress = xform_stripped_oid('.1.3.6.1.2.1.4.22.1.2', $device);
                mactrack_debug('atPhysAddress data collection complete Nexus');
                $atNetAddress = xform_stripped_oid('.1.3.6.1.2.1.4.22.1.3', $device);
                mactrack_debug('atNetAddress data collection complete Nexus');
        }
[mactrack-nexus10.9.76.4820190201.log](https://github.com/Cacti/plugin_mactrack/files/2823631/mactrack-nexus10.9.76.4820190201.log)
`


2019/02/01 17:00:58 - MACTRACK DEBUG: atNetAddress data collection complete Nexus
--
2019/02/01 17:00:56 - MACTRACK DEBUG: atPhysAddress data collection complete Nexus
2019/02/01 17:00:31 - MACTRACK DEBUG: atifIndexes data collection complete Nexus

**Comment by cigamit** [comment]
Take another crack at the collection.  Making more fixes.

**Comment by cigamit** [comment]
Did this start after upgrading or after implementing some of my recent changes?

**Comment by cigamit** [comment]
After you make the updates, if there are still problems, update your lib/snmp.php in Cacti.  I backed off a change that went into 1.2.1.  One liner.

**Comment by jdcoats** [comment]
after 
Latest commit 75f8fcc 2 days ago and update of snmp.php
[mactrack_scanner.txt](https://github.com/Cacti/plugin_mactrack/files/2828222/mactrack_scanner.txt)

**Comment by jdcoats** [comment]
The above include failure is the result of the include typo in mactrack_scanner.php

> -include_once('./plugins/mactrack/lib/mactrack_actions.php');
+include_once('./plugins/mactrack/mactrack_actions.php');

Still need the Undefined offset worked out which is why the mac to ip association isnt working reliably.

**Comment by jdcoats** [comment]
Confirming with current pull mactrack works! Pointing out that it is only reasonable with php 5.6 as of today. With php7.1 the polling of a Cisco switch with 200+ vlans takes over 20minutes and terminates. The same polling with php5.6 takes seconds

**Comment by cigamit** [comment]
Try again on a test system on php7.1 and let me know the results.

**Comment by jdcoats** [comment]
confirmed working with php 7.1 runs at same speed as php5.6 and no php errors. Thanks!

**Comment by cigamit** [comment]
Cool.  Closing then.
