### ISSUE TITLE
DB Exec Failed!, Error: PDOStatement::execute

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#106]
2019/02/19 11:01:39 - CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[251]:log_mactrack_statistics(), /plugins/mactrack/poller_mactrack.php[968]:db_execute(), /lib/database.php[189]:db_execute_prepared())
--
2019/02/19 11:01:39 - CMDPHP ERROR: A DB Exec Failed!, Error: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound

**Comment by cigamit** [comment]
Should be all set now.
