### ISSUE TITLE
>MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#107]
> The issue at this point is only regarding the message
"MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress"

This issue does still exist. It doesn't cause a problem. It just makes red marks in your clean green log :)
It is seen when using a 1 minute polling interval. The error is seen every minute that mactrack is running. 
![untitled](https://user-images.githubusercontent.com/42470924/53175070-4129ef80-35b9-11e9-9047-0d10a80528c5.png)
I guess I could just change it to be a system message instead of an error since it has always been there. This issue has existed since the 1st versions of mactrack i think.

_Originally posted by @jdcoats in https://github.com/Cacti/plugin_mactrack/issues/39#issuecomment-466014712_

**Comment by cigamit** [comment]
I thought briefly of asking that this issue be closed, and to open another one ;)  Should be resolved now.

**Comment by jdcoats** [comment]
Thanks! :) FYI, during the upgrade it did throw the following, dunno if its transient or if its something that should be cleaned up.

> 

2019/02/25  08:07:39 - CMDPHP SQL Backtrace:  (/index.php[25]:include(),  /include/auth.php[28]:require_once(),  /include/global.php[403]:include_once(),  /include/global_settings.php[2268]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:mactrack_config_settings(),  /plugins/mactrack/setup.php[552]:mactrack_check_upgrade(),  /plugins/mactrack/setup.php[99]:mactrack_database_upgrade(),  /plugins/mactrack/includes/database.php[294]:mactrack_add_column(),  /plugins/mactrack/setup.php[184]:db_execute(),  /lib/database.php[189]:db_execute_prepared())
--
2019/02/25 08:07:39 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'device_name'

**Comment by jdcoats** [comment]
FYI, mactrack broke again after this update and I didn’t save my previous version :/ . Please see the new issues opened.

Thanks!
Dan
