### ISSUE TITLE
 String size overflow in file:cacti/plugins/mactrack/lib/mactrack_functions.php on line: 1774

### ISSUE THREAD

**Issue by earicmartin** [Cacti/plugin_mactrack#111]
**Describe the bug**

2019/03/07 13:37:37 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'mactrack'
--
2019/03/07 13:37:37 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2019/03/07 13:37:37 - ERROR PHP ERROR in Plugin 'mactrack': String size overflow in file: cacti/plugins/mactrack/lib/mactrack_functions.php on line: 1774
2019/03/07 13:36:50 - MACTRACK DEBUG: 445 IP's require resolving this pass
2019/03/07 13:36:49 - MACTRACK DEBUG: MAC VLANs in VLAN Table Updated

This happens every time it trys to run. I have about 45 devices installed right now  3 different sites but if i remove some of the device sit will work seems like it cannot handle all my devices. Is there something i can change i am trying to add in close to 100 devices.

**Comment by earicmartin** [comment]
I found it gets to these steps when it breaks

**Comment by earicmartin** [comment]
ck/mactrack_scanner.php -id=124 -d]
2019/03/07 14:07:39 - MACTRACK DEBUG: A process cycle launch just completed.
2019/03/07 14:07:43 - MACTRACK DEBUG: Waiting on 2 with id = [-1, 0, 123, 124] to complete prior to exiting.
2019/03/07 14:07:45 - MACTRACK DEBUG: Waiting on 2 with id = [-1, 0, 123, 124] to complete prior to exiting.
2019/03/07 14:07:47 - MACTRACK DEBUG: Waiting on 2 with id = [-1, 0, 123, 124] to complete prior to exiting.
2019/03/07 14:07:49 - MACTRACK DEBUG: Waiting on 2 with id = [-1, 0, 123, 124] to complete prior to exiting.
2019/03/07 14:07:51 - MACTRACK DEBUG: Waiting on 1 with id = [-1, 0, 123] to complete prior to exiting.
2019/03/07 14:07:53 - MACTRACK DEBUG: Waiting on 1 with id = [-1, 0, 123] to complete prior to exiting.
2019/03/07 14:07:55 - MACTRACK DEBUG: Waiting on 1 with id = [-1, 0, 123] to complete prior to exiting.
2019/03/07 14:07:57 - MACTRACK DEBUG: Waiting on 1 with id = [-1, 0, 123] to complete prior to exiting.
2019/03/07 14:07:59 - MACTRACK DEBUG: Waiting on 1 with id = [-1, 0, 123] to complete prior to exiting.
2019/03/07 14:08:01 - MACTRACK DEBUG: Waiting on 1 with id = [-1, 0, 123] to complete prior to exiting.
2019/03/07 14:08:03 - MACTRACK DEBUG: Waiting on 1 with id = [-1, 0, 123] to complete prior to exiting.
2019/03/07 14:08:05 - MACTRACK DEBUG: Waiting on 0 with id = [-1, 0] to complete prior to exiting.
2019/03/07 14:08:05 - MACTRACK DEBUG: Interum IP addresses to MAC addresses association pass complete.
2019/03/07 14:08:05 - MACTRACK DEBUG: MAC addresses to Vendor MACS association pass complete.
2019/03/07 14:08:05 - MACTRACK DEBUG: MAC VLANs in VLAN Table Updated.

**Comment by jdcoats** [comment]
what is memory_limit in php.ini? Try raising it? mine is 2G

**Comment by earicmartin** [comment]
Mine is at 4096M

**Comment by cigamit** [comment]
This should be resolved now.  I've migrated to a pear module for reverse DNS resolution.  Much more reliable I think.

**Comment by jdcoats** [comment]
Wow, looks like big changes. I’ll test tomorrow morning. :)


——
Dan

**Comment by earicmartin** [comment]
2019/03/08 13:59:15 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
--
2019/03/08 13:59:15 - ERROR PHP ERROR in Plugin 'mactrack': Class 'Net_DNS2_Resolver' not found in file: /usr/share/cacti/plugins/mactrack/mactrack_resolver.php on line: 121
2019/03/08 13:59:15 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mactrack/mactrack_resolver.php[34]:include_once(), /plugins/mactrack/mactrack_resolver.php[34]:CactiErrorHandler())
2019/03/08 13:59:15 - ERROR PHP WARNING in Plugin 'mactrack': include_once(): Failed opening '/usr/share/cacti/plugins/mactrack/incudes/Net_DNS2/Net/DNS2.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in file: /usr/share/cacti/plugins/mactrack/mactrack_resolver.php on line: 34
2019/03/08 13:59:15 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mactrack/mactrack_resolver.php[34]:include_once(), /plugins/mactrack/mactrack_resolver.php[34]:CactiErrorHandler())
2019/03/08 13:59:15 - ERROR PHP WARNING in Plugin 'mactrack': include_once(/usr/share/cacti/plugins/mactrack/incudes/Net_DNS2/Net/DNS2.php): failed to open stream: No such file or directory in file: /usr/share/cacti/plugins/mactrack/mactrack_resolver.php on line: 34

**Comment by cigamit** [comment]
Resolved now.  You should be all set.  I had to move some files around, so if you are using clone, you will be okay, otherwise remove the directory `includes/Net_DNS2`.
