### ISSUE TITLE
cacti 1.1.38 mactrack 4.2  ED IP ADDRESS - ED DNS Hostname

### ISSUE THREAD

**Issue by jumpy-frog** [Cacti/plugin_mactrack#116]
I use cacti 1.1.38 and mactrack 4.2 
I can't get the ED IP address and ED DNS Hostname to work.
My dns are correctly configured both in the machine and on mactrack and but mactrack does not resolve the names and ip on the switch ports Do you know how to solve this thing ?? Thanks for any help you will give me

**Comment by jdcoats** [comment]
are you saying that you do not see either of IP address and the dns name or you do see the IP address but just not resolving dns name?

**Comment by jumpy-frog** [comment]
I mean I only see the switch's ip.
I see the client's mac the switch port where it is connected but I DO NOT see its ip and its name. Look attached and thank you for your reply
<img width="755" alt="Schermata 2019-03-20 alle 15 21 06" src="https://user-images.githubusercontent.com/48761149/54691875-534d6e00-4b24-11e9-9bb2-aac702a00f24.png">

**Comment by jdcoats** [comment]
okay, I'm guessing that you are only scanning layer 2 switches then. You will also need to scan the Layer3 switch or router where the arp table is to map the mac address to ip address.

**Comment by jumpy-frog** [comment]
I have two buildings connected in bridge between them with a single layer3 core switch
I have the same switches on both buildings.
in a building I see everything correctly
in another no
I don't understand .... I'm going crazy.
While if I use an old cacti relesease 08.8a with mactrack 2.9 I see everything on both palaces .......
look at the pictures- this image is of the building where I see everything
<img width="749" alt="Schermata 2019-03-20 alle 15 52 23" src="https://user-images.githubusercontent.com/48761149/54694868-3e270e00-4b29-11e9-9fe3-73c2fed03725.png">

**Comment by jumpy-frog** [comment]
and this where I see nothing
<img width="749" alt="Schermata 2019-03-20 alle 15 58 26" src="https://user-images.githubusercontent.com/48761149/54694940-5f87fa00-4b29-11e9-9dee-5bf9b811bb81.png"> and there are the same switches in  configuration layer 2 (switch/hub no arp table )

**Comment by jdcoats** [comment]
the arp table for the endpoints connected to both L2 switches is on the same L3 switch and you see them in the arp cache there?

**Comment by jumpy-frog** [comment]
I am installing a server with cacti 1.1.38 and mactrack 442: a core switch layer for all lan (here I see the arp table of all the lan with public and private ip mac address) connected to a layer 2 bridge switch (to connect a other building) on this bridge, however, I see only the private IPs of the switches and NOT those of the hosts in ARP table. I have a cacti 08.8a server running with mactrack 2.9. Identical configuration described above. everything works. I see everything. I don't understand .... thanks again for your time spent ...

**Comment by jdcoats** [comment]
If this is a new build then I would suggest Cacti 1.2.2 and Mactrack 4.4 as there have been many fixes to both

**Comment by jumpy-frog** [comment]
they are reliable and stable versions  ?!?!?!

**Comment by jdcoats** [comment]
That is what I am running in production. Definitely more stable than 1.1.38 and 4.2 were for me.

**Comment by jumpy-frog** [comment]
OK jdcoats thank you very much for your time and thanks again

**Comment by cigamit** [comment]
Closing
