### ISSUE TITLE
Undefined property: Net_DNS2_RR_CNAME::$ptrdname in file

### ISSUE THREAD

**Issue by earicmartin** [Cacti/plugin_mactrack#118]
**Describe the bug**

2019/05/07 18:35:32 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_resolver.php[156]:CactiErrorHandler())
--
2019/05/07 18:35:32 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined property: Net_DNS2_RR_CNAME::$ptrdname in file: /usr/share/cacti/plugins/mactrack/mactrack_resolver.php on line: 156

**Comment by TheWitness** [comment]
Resync with latest develop and try again.  The Net_DNS2 was way out of date.

**Comment by TheWitness** [comment]
I've don another commit on this.  Pretty sure it's resolved now.
