### ISSUE TITLE
MacTrack development status

### ISSUE THREAD

**Issue by PhilipSchmid** [Cacti/plugin_mactrack#12]
Hi there,

We are using MacTrack for years now and it has been a lifesaver. Thanks for that!

As I recently checked the MacTrack repository and realized, that there were some new development activities. I now wonder if you guys plan to release a new version in the near future? The last release was on 18th Aug 2010 and for a long time it looked like MacTrack was dead.

Thanks for your answer.

Regards,
Philip

**Comment by cigamit** [comment]
It's essentially in maintenance mode here on GitHub.  The plugin has been updated to be compatible with Cacti 1.0+.  Any changes at this point will be to keep it functional.  So, once you dip your toes into Cacti 1.0, you should start testing this plugin, reporting issues, or submitting pull requests with fixes.
