### ISSUE TITLE
PHP Backtrace

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#13]
Hi, I found these errors on Cacti.log

Cacti 1.0.3
MacTrack 4 from git without the latest commits.
PHP 5.4.16

> 2017-02-27 14:00:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_scanner.php: 167 call_user_func_array)(get_IOS_dot1dTpFdbEntry_ports)(/plugins/mactrack/lib/mactrack_cisco.php: 427 CactiErrorHandler)(/lib/functions.php: 4242 cacti_debug_backtrace)
> 2017-02-27 14:00:10 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined variable: portTrunking in file: /usr/share/cacti-1.0.3/plugins/mactrack/lib/mactrack_cisco.php on line: 427
> 2017-02-27 14:00:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_scanner.php: 167 call_user_func_array)(get_IOS_dot1dTpFdbEntry_ports)(/plugins/mactrack/lib/mactrack_cisco.php: 427 CactiErrorHandler)(/lib/functions.php: 4242 cacti_debug_backtrace)
> 2017-02-27 14:00:10 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined variable: ifName in file: /usr/share/cacti-1.0.3/plugins/mactrack/lib/mactrack_cisco.php on line: 427

Let me know if you need further details.

**Comment by cigamit** [comment]
Resolved.
