### ISSUE TITLE
Feature Request. Check for Duplicates when importing devices from the main host table

### ISSUE THREAD

**Issue by vKnmnn** [Cacti/plugin_mactrack#133]
Currently one can import a device multiple times. I think we shouldn't be able to do that.

When selecting "Delete" in the data_sources managemnt, we are not able to select undeletable datasources. Maybe we can do something similar here. 
Make Devices whose hostname,description combination already appear in the mac_track_devices table unselectable.

**Comment by TheWitness** [comment]
You will need to explain how your are able to do this, if you try to import a second time, unless you have changed the Site ID or the SNMP Port for the device.  Can you confirm that you are either doing, or not doing this?

**Comment by vKnmnn** [comment]
I no longer work at the place where this occurs, so i cannot confirm this anymore.

**Comment by xmacan** [comment]
Tested - device is not added more times. Closing
