### ISSUE TITLE
Brocade ICX 7250 & 7750 Switch Support

### ISSUE THREAD

**Issue by ManrajSingh1** [Cacti/plugin_mactrack#14]
Hi

I tried creating an account on the cacti forums and was unable to do so to contact this plugin creators.

I was wondering if it would be possible to get support for the Brocade ICX 7250 & 7750 switches, somehow the Cisco IOS function does poll interface information, however it does not get IP or MAC addresses.

**Comment by smiles1969** [comment]
The Cacti Group now maintains this plugin. The original author no longer does.

I believe a custom "lib/mactrack_brocade.php" is going to have to be developed to define the proper MAC address and IP scanning function for Brocade. These have been previously developed for IOS, extreme, etc. So if the existing MAC and IP address scanning functions do not work for brocade, I believe this will need to be written and submitted as a pull request.

Not sure if anyone on the dev team has a brocade device to use, but I don't, or I would be glad to help.

You may want to try some of the Foundry scanning functions, I believe some of their switches are the same as Brocade.

**Comment by ManrajSingh1** [comment]
The IP address scanning function for the Brocade Switch worked after waiting a little bit, I used the foundry scanning function and that also worked. Seems to be working fine at the moment, haven't noticed any error s in the data that has been pooled.
