### ISSUE TITLE
Mactrack PHP code error with Mailer class

### ISSUE THREAD

**Issue by DanielMarquezCortes** [Cacti/plugin_mactrack#140]
Hi all,

I have installed a new version of Cacti to replace my older one. Both installations have the mactrack plugin installed (version 4.4) and working properly. However, I have the same mistake in de PHP code I had to solve.

I received mactrack plugin errors when I configured the MAC Watch

 2020/09/10 12:37:37 - ERROR PHP ERROR in Plugin 'mactrack': Uncaught Error: Class 'Mailer' not found in /var/cacti/plugins/mactrack/lib/mactrack_functions.php:3080 Stack trace: #0 /var/cacti/plugins/mactrack/poller_mactrack.php(835): mactrack_mail('sistemas.comseg...', 'mactrack.cacti@...', 'MACTrack Cacti ...', 'MACAUTH Notific...', 'Mac Address 7C:...', '') #1 /var/cacti/plugins/mactrack/poller_mactrack.php(228): collect_mactrack_data(1599734105.7627, 0) #2 {main} thrown in file: /var/cacti/plugins/mactrack/lib/mactrack_functions.php on line: 3080 

I solved this issue with these two steps:

 - I installed the plugin "settings" in the cacti folder /<your installation folder>/cacti/plugins/settings.
 - I changed the sourcecode in that line "/var/cacti/plugins/mactrack/lib/mactrack_functions.php:3080" and I added the mailer class reference.

function mactrack_mail($to, $from, $fromname, $subject, $message, $headers = '') {
	global $config;
	
	// NEW LINE INCLUDED
	include_once($config['base_path'] . '/plugins/settings/include/mailer.php');
	
	$subject = trim($subject);

	$message = str_replace('<SUBJECT>', $subject, $message);

This solves the problem, but I get the following issue:

2020/09/14 10:02:36 - ERROR PHP DEPRECATED in Plugin 'settings': Methods with the same name as their class will not be constructors in a future version of PHP; Mailer has a deprecated constructor in file: /var/cacti/plugins/settings/include/mailer.php on line: 27 

Best regards,
Daniel M.

**Comment by TheWitness** [comment]
We are not supporting the old Cacti 0.8.x series any longer.  Best you upgrade to Cacti 1.2.14.

**Comment by DanielMarquezCortes** [comment]
Thanks for your answer. However, I use Cacti 1.2.12 and Mactrack 4.4

**Comment by TheWitness** [comment]
Well, the settings plugin is no longer required since Cacti 1.x.  So, you must be hacking.

**Comment by DanielMarquezCortes** [comment]
That was I said, I had to installed that plugin and changed the sourcecode to include the Mailer class, since in Mactrack that class is used without being properly referenced.

**Comment by TheWitness** [comment]
Well, I've never been good at reading ;)  I'll have a look later today.  Right now, I have to get to workie.

**Comment by TheWitness** [comment]
Okay, update the plugin to the develop version and try again.  You should no longer need the old settings plugin.

**Comment by DanielMarquezCortes** [comment]
Ok. Thank you!
