### ISSUE TITLE
Dot1x search function does not work

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#141]
I've tried search for username, IP address and mac address in the dot1x search field, search does not produce results.

**Comment by TheWitness** [comment]
Awesome.

**Comment by TheWitness** [comment]
I just did an update Dan.  Try again.

**Comment by jdcoats** [comment]
The search field still does not appear to work. The filters for Port Name, IP & Mac work but the "Search" still does not.

**Comment by TheWitness** [comment]
Oh, okay.  What fields are you assuming it searches?

**Comment by TheWitness** [comment]
And would you prefer regular expressions of simple search?

**Comment by jdcoats** [comment]
I expected that maybe it should work like this: but mainly the username since other fields are already filterable. Maybe Just make a username filter? 👍 
![dot1x-search](https://user-images.githubusercontent.com/42470924/97119463-c6e33400-16e6-11eb-9a5e-2c816ccca2fb.png)

**Comment by jdcoats** [comment]
okay, with recent commit, I thought it worked on my 1st search but then when confirming a few it does not and I see 
```

020/10/25 17:09:14 - CMDPHP SQL Backtrace: (/plugins/mactrack/mactrack_view_dot1x.php[43]:mactrack_view_dot1x(), /plugins/mactrack/mactrack_view_dot1x.php[387]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
--
2020/10/25 17:09:14 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'mti.ifName' in 'where clause'
2020/10/25 17:08:49 - CMDPHP SQL Backtrace: (/plugins/mactrack/mactrack_view_dot1x.php[43]:mactrack_view_dot1x(), /plugins/mactrack/mactrack_view_dot1x.php[387]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
2020/10/25 17:08:49 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'mti.ifName' in 'where clause'
2020/10/25 17:08:26 - CMDPHP SQL Backtrace: (/plugins/mactrack/mactrack_view_dot1x.php[43]:mactrack_view_dot1x(), /plugins/mactrack/mactrack_view_dot1x.php[387]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
2020/10/25 17:08:26 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'mti.ifName' in 'where clause'


```

**Comment by TheWitness** [comment]
Try again.

**Comment by jdcoats** [comment]
okay progress, mac ip and port are searchable but username is not so you can find mac, ip or port with either the search or the filter options but username cannot be searched, so it needs either a filter or just to work in search.

**Comment by TheWitness** [comment]
Give it one more shot.

**Comment by jdcoats** [comment]
works as expected :) Thanks!
