### ISSUE TITLE
cannot edit device types or devices as expected

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#149]
Create a device type.
Edit that device type Switch/Hub to Switch/Router or similar. Result is not edited but a new duplicate with your modification is created.
Delete the one that you do not want and both are deleted.
Workaround: Do not edit device type, just delete and create new.

This same issue exists for Mactrack devices themselves. If you edit a device to change the site from X to Y it doesn't edit the device, it duplicates it in the new site.
Delete the duplicate and it deletes both.

This site issue would be better to use the Cacti site associated to the Cacti device instead of having to create all of the same sites twice both in Cacti and in Mactrack.

**Comment by xmacan** [comment]
I think that it is fixed, cannot reproduce
