### ISSUE TITLE
Missing tables when installing Mactrack 4.4

### ISSUE THREAD

**Issue by Cramin** [Cacti/plugin_mactrack#154]
Runing Cacti 1.2.16 and Cacti Spine 1.2.16 on Debian 10.

**Describe the bug**
Mysql tables are not created because of missing default value for port_number.

**Plugin
 - Version: 4.4
 - Source: github
 - Identifer: -

**Desktop
 - OS: Windows 10
 - Browser Opera
 - Version 73.0.3856.260

I make a commit  and add '0' as default value for port_number and tables are created and MACs and IPs are displayed.
https://github.com/Cramin/plugin_mactrack/commit/43dcaaff09bfa05dad92aa98a1109f5032374d82

**Comment by TheWitness** [comment]
Which table dude?

**Comment by Cramin** [comment]
Check my commit, there are three tables, my mistake
api_plugin_db_table_create ('mactrack', 'mac_track_ip_ranges', $data);
api_plugin_db_table_create ('mactrack', 'mac_track_oui_database', $data);
api_plugin_db_table_create ('mactrack', 'mac_track_snmp_items', $data);

**Comment by TheWitness** [comment]
This was likely corrected by #161 and #160
