### ISSUE TITLE
mactrack develop install cacti 1.2.16 error:2021/01/05 18:47:33 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined offset: 211 in file: /var/www/html/plugins/mactrack/lib/mactrack_functions.php on line: 721

### ISSUE THREAD

**Issue by flying-bigbird** [Cacti/plugin_mactrack#155]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheWitness** [comment]
duplicate
