### ISSUE TITLE
Port no and Port name not showing in Mac Address Tab

### ISSUE THREAD

**Issue by ngchch2013** [Cacti/plugin_mactrack#162]
Using Cacti 1.2.4 and MacTrack 4.4, everything is work fine but only in MAC Address tab, no Port Number and Port Name is displaying, Port Number field is "0" and Port Name is empty.

Device type is C2960X, MAC Address Scanning Function is using get_IOS_dot1dTpFdbEntry_ports.

**Comment by JoeyChen-NTUT** [comment]
--- 4.3 / 4.4 ---
feature: Switch port_number to integer type of performance reasons

Seen is change by dev teams but We Still Needs real port number for some like Cisco Netgear...etc has like 1/0/1 interface name

Update:
all in column are show 0 not mapping to mac_track_interfaces
but mac_track_ips had port_number...

**Comment by jdcoats** [comment]
This is working fine for me. Port number and port name are correct.

**Comment by JoeyChen-NTUT** [comment]
> This is working fine for me. Port number and port name are correct.

What device are you using? I'm use Cisco Device and it's didn't work

**Comment by jdcoats** [comment]
all Cisco switches

**Comment by JoeyChen-NTUT** [comment]
> all Cisco switches

In my environment had more than 300 Cisco device since 2950 to 9500 there isn't have any result of device has port_number  
![image](https://user-images.githubusercontent.com/40187978/146474590-1e8c35ff-4aaf-4979-806c-715a5eb8922c.png)

There is my Device Type Setting
![image](https://user-images.githubusercontent.com/40187978/146476165-b172dfab-d2b9-4da1-ad6e-86b7320f4956.png)


Any idea for help me with it thanks.

**Comment by TheWitness** [comment]
You guys should compare schemas.  Maybe port_num was converted to integer, which would cause this issue.

**Comment by jdcoats** [comment]
```
MariaDB [cacti]> describe mac_track_ports;
+--------------+---------------------+------+-----+---------------------+-------+
| Field        | Type                | Null | Key | Default             | Extra |
+--------------+---------------------+------+-----+---------------------+-------+
| site_id      | int(10) unsigned    | NO   | MUL | 0                   |       |
| device_id    | int(10) unsigned    | NO   | PRI | 0                   |       |
| hostname     | varchar(40)         | NO   | MUL |                     |       |
| device_name  | varchar(100)        | NO   | MUL |                     |       |
| vlan_id      | varchar(5)          | NO   | MUL | N/A                 |       |
| vlan_name    | varchar(50)         | NO   | MUL |                     |       |
| mac_address  | varchar(20)         | NO   | PRI |                     |       |
| vendor_mac   | varchar(8)          | YES  | MUL |                     |       |
| ip_address   | varchar(20)         | NO   | MUL |                     |       |
| dns_hostname | varchar(200)        | YES  | MUL |                     |       |
| port_number  | varchar(20)         | NO   | PRI |                     |       |
| port_name    | varchar(50)         | NO   | MUL |                     |       |
| scan_date    | timestamp           | NO   | PRI | 0000-00-00 00:00:00 |       |
| authorized   | tinyint(3) unsigned | NO   | MUL | 0                   |       |
+--------------+---------------------+------+-----+---------------------+-------+
14 rows in set (0.002 sec)
```

**Comment by jdcoats** [comment]
Also, if you would like to separate device types you can do it like this.
![image](https://user-images.githubusercontent.com/42470924/146550676-0b387030-8b4c-426f-ab52-5996712f65f9.png)

**Comment by TheWitness** [comment]
That image takes me back to 2006 when MacTrack was so fresh.  You look at it and it seems just a tiny plugin, but when populated with a few k hosts and 40 odd sites, it's marvelous.

**Comment by JoeyChen-NTUT** [comment]
> You guys should compare schemas. Maybe port_num was converted to integer, which would cause this issue.

Yes, I think it's root cause  
I just install the latest version from dev branch and my DB port_number column schemas it's integer  
so the current schemas it's varchar??

**Comment by jdcoats** [comment]
@TheWitness You've been doing good work a long time 🥇

**Comment by TheWitness** [comment]
Oh boy, maybe not.  Keep this bug open...

**Comment by TheWitness** [comment]
Just run the alter to make it varchar.

**Comment by JoeyChen-NTUT** [comment]
> Just run the alter to make it varchar.
--- 4.3 / 4.4 ---
feature: Switch port_number to integer type of performance reasons

https://github.com/Cacti/plugin_mactrack/commit/92e8b5d4fc4394ca869a4e28124a6f8bd1df8694

so did I need to change back to varchar? for fix this issue?

**Comment by TheWitness** [comment]
Shame on me.  But I coding blind. I have a bunch of Mikrotiks in the house though.

**Comment by JoeyChen-NTUT** [comment]
> Shame on me. But I coding blind. I have a bunch of Mikrotiks in the house though.

and it's issue has inconsistent schema with sql file and mactrack_convert(https://github.com/Cacti/plugin_mactrack/blob/develop/mactrack_convert.php)  in line 125

**Comment by TheWitness** [comment]
Fixed.
