### ISSUE TITLE
arp table not being retrieved from VRF containers

### ISSUE THREAD

**Issue by jaxson5** [Cacti/plugin_mactrack#163]
**Describe the bug**
There is no arp translation received from layer 3 switches/routers into mactrack when they are contained in a VRF.

**To Reproduce**
In the MAC Address tab there are no 'ED IP Address' or 'ED DNS Hostname' from edge devices since it can't interigate the arp table which sits within the VRF.

**Expected behavior**
arp entries added to the database from within a VRF

**Screenshots**

**Plugin (please complete the following information):**
 - Version: 1.2.16
 - Source: github

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Any, but mostly Chrome
 - Version 65

**Additional context**
I understand this might be a limitation of snmp querying, but thought it was worth checking with people who know more about  it than I.

**Comment by jaxson5** [comment]
When I completed an snmpwalk as below it gave me the list of MAC addresses from the VRFs
snmpwalk -v2c -c \<string\> \<VSS IP\> .1.3.6.1.2.1.3.1.1.2

for example:
iso.3.6.1.2.1.3.1.1.2.216.1. \<ED IP Address\> = Hex-STRING: \<ED MAC Address\>

I'll try to reproduce this on the other VSSs and see if this string is consistent.

**Comment by jaxson5** [comment]
Ok it's consistent under  .1.3.6.1.2.1.3.1.1.2 for these Cisco c6807s at least:

Sample:
iso.3.6.1.2.1.3.1.1.2.216.1.10.252.17.42 = Hex-STRING: 58 DC 73 A6 52 34

Any way to get this information incorporated into mactrack?

**Comment by TheWitness** [comment]
Well, you need to add it to the arp scanning functions in the mactrack_cisco.php library function.  See if you are able to do this.  The arp functions are pretty strait forward.  Just work your way through it.  Then, create a pull request.  You need to write the function, and then add it to the registration function for mactrack_cisco.php.  That should be at the very top of the file.  Once done, for each device impacted, you will simply change the arp scanning function to use your new function.

**Comment by jaxson5** [comment]
So it seems I was wrong. The Cisco scanner grabs the end point IPs and puts them in mac_track_ips table. This isn't referenced by  mactrack_view_macs.php, but I have modified it for now and am testing. Seems good so far.

**Comment by TheWitness** [comment]
A pull request would be appreciated.  I really don't work too much on this plugin any more these days as I've been out of the Networking world for almost 15 years.  Was a great plugin way back then though.  MacTrack was really my first plugin.

**Comment by jaxson5** [comment]
Confirmed working in new devel. If you are using an MPLS PE for the arp translations then make sure you set that device to use the get_cisco_vrf_arp scanning function.
