### ISSUE TITLE
Wrong URL on the main tab in the UI

### ISSUE THREAD

**Issue by uvmonger** [Cacti/plugin_mactrack#172]
Get a 404 error when clicking on the main tab Mactrack in Cacti. The tab for the Mactrack tab goes to http://hostname/cacti/plugins/mactrack/mactrack_view_.php instead of http://hostname/cacti/plugins/mactrack/mactrack_view_sites.php.

Cacti version  1.2.21
Mactrack 4.4
RHEL 8.6
mysql  Ver 15.1 Distrib 10.3.32-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by TheWitness** [comment]
Fixed.
