### ISSUE TITLE
CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.mac_track_arp' doesn't exist 

### ISSUE THREAD

**Issue by rcsmota** [Cacti/plugin_mactrack#173]
I'm running a fresh installation of Cacti 1.2.21 with Mactrack 4.4 on Debian 11 and get this logs.

![image](https://user-images.githubusercontent.com/31240306/175321479-71d9952d-b1a2-4974-addc-2e99f9e6e12e.png)

Look at mysql really don't exist a mac_track_arp table.

![image](https://user-images.githubusercontent.com/31240306/175321727-ae1bdcfd-8154-401e-a513-5cf5cd8c11e4.png)

Can I add manually the table on cacti data base? 

Thanks

**Comment by TheWitness** [comment]
It's likely that your SQL mode was not correct.  How did you install the tables?

**Comment by TheWitness** [comment]
Can you please update to the latest develop.  I don't see that table anywhere, which is odd.  What line of what file was that error.  Need more information.

**Comment by rcsmota** [comment]
Hi @TheWitness. The tables was installed when I install plugin. Download on Github, unzip on <cacti_path>/plugins/, rename and install via GUI.

The full messages are, it repeats itself several times

 CMDPHP SQL Backtrace: (/plugins/mactrack/poller_mactrack.php[229]:collect_mactrack_data(), /plugins/mactrack/poller_mactrack.php[614]:db_fetch_row(), /lib/database.php[532]:db_fetch_row_prepared(), /lib/database.php[552]:db_execute_prepared()) 
CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.mac_track_arp' doesn't exist 

![image](https://user-images.githubusercontent.com/31240306/176393369-fc50c240-63dd-4d86-a489-e0bde4805d4c.png)

 
I think is on last developer version.

![image](https://user-images.githubusercontent.com/31240306/176392018-68c1b940-0341-46fc-8f45-4b238d8d0920.png)

what else can i do to help?

Thanks.

**Comment by TheWitness** [comment]
Use the latest develop version.

**Comment by ralex75** [comment]
Hi, I have same issue:
02-07-2022 11:35:10 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.mac_track_arp' doesn't exist
I have downloaded latest develop version .zip.
In database.php no code line to create mac_track_arp table.
Cacti version 1.2.19.

**Comment by TheWitness** [comment]
This has been resolved now.  You can test the latest github.

**Comment by rcsmota** [comment]
Hi @TheWitness.

It's all working now. Thank you very much.
