### ISSUE TITLE
wrong function name db_execute_preapred

### ISSUE THREAD

**Issue by ralex75** [Cacti/plugin_mactrack#174]
**Describe the bug**
ERROR PHP ERROR in Plugin 'mactrack': Uncaught Error: Call to undefined function db_execute_preapred() in /usr/share/cacti/plugins/mactrack/lib/mactrack_3com.php:73 

 - Version: 4.5 develop

**Comment by TheWitness** [comment]
Okay fixed. Thanks for reporting!
