### ISSUE TITLE
mac_track_ips duplicates

### ISSUE THREAD

**Issue by ms32035** [Cacti/plugin_mactrack#176]
Why `scan_date` is part of the primary_key for `mac_track_ips`? It causes duplications as records are never updated by the `REPLACE` sql statement

**Comment by ms32035** [comment]
Same problem with `mac_track_ports`

**Comment by ms32035** [comment]
Actually, upon further look, it's probably by design.

**Comment by TheWitness** [comment]
Yup, we want to track you as you move from cubical to cubical, at least we used to.  Was a great tool finding computers with virus' in the old days.  Have not been actively developing it for years, but it works great in my home lab :)
