### ISSUE TITLE
Feature request: Add dot1x values

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#18]
Hi there,

It is a really good plugin. I've never used it before but I'm giving it a try while testing Cacti 1.x

It would be nice to be able to read the authenticantion state of ports by polling this OID .1.3.6.1.4.1.9.9.656.1.4.1.1.5

And also fetch some other values based on CISCO-AUTH-FRAMEWORK-MIB

> Username = .1.3.6.1.4.1.9.9.656.1.4.1.1.10
> MAC = .1.3.6.1.4.1.9.9.656.1.4.1.1.2
> IP ADDR = .1.3.6.1.4.1.9.9.656.1.4.1.1.4
> Guest VLAN ID = .1.3.6.1.4.1.9.9.220.1.1.1.3 | .1.3.6.1.4.1.9.9.220.1.1.1.4 (true/false validation)
> Port Mode = .1.3.6.1.4.1.9.9.220.1.1.1.1
> Domain = .1.3.6.1.4.1.9.9.656.1.4.1.1.6
> Violation action = .1.3.6.1.4.1.9.9.656.1.2.1.1.10
> Voice VLAN = .1.3.6.1.4.1.9.9.68.1.5.1.1.1

Some DHCP Snooping as well? like validating the IP discovered is actually in dhcp snooping database.

I'd love to have this into MacTrack and then I'm thinking I could provide a tool to force port to re-authenticate o forced authorized, etc. It's a pain in the ass provide support for dot1x T.T

If you need snmpwalks I'm happy to help.

No idea about other vendors but i could help with the research but with real testing.

**Comment by jpobeda** [comment]
Gathering data for this.

**Comment by cigamit** [comment]
Do the walks and then lets discuss how to present the data.  Maybe another sub-tab?

**Comment by jpobeda** [comment]
I've got the walks, need to suppress sensitive data before uploading them. 

I was thinking on a sub-tab as well and provide a new function for switches to use instead of the get_standard_arp_table, called get_dhcp_snooping_db or something like that. 

So when you've got switches with dhcp snooping running you don't waist time looking at the arp tables because you'd get the whole lot and for different vlans as well, per switch.

1 more scanning function get_dot1x_table, per switch as well. This one wouldn't replace anyone so It'll be a new scanning function option to choose.

I'm still thinking about the switchport port-security one because the useful part of that is to find/track where certain MAC has been sticky MAC to what ports on which switches. In cases where you need to clear those MACs or something like that.

What do you think?

**Comment by jpobeda** [comment]
Dot1x SNMPWALKs

[cafSessionTable.log.1.txt](https://github.com/Cacti/plugin_mactrack/files/1286697/cafSessionTable.log.1.txt)

DHCP SNOOPING SNMPWALKs
This one should be easy enough to match IP + Iface to existing MacTrack database. Not sure how to present this data though

[cdsBindings.log.txt](https://github.com/Cacti/plugin_mactrack/files/1286703/cdsBindings.log.txt)

PORT SECURITY SNMPWALKs
Maybe another sub-tab I think there will be ifaces without security features enabled, ifaces w/dot1x and ifaces w/portsecurity.

[cpsIfPortSecurity.log.txt](https://github.com/Cacti/plugin_mactrack/files/1286705/cpsIfPortSecurity.log.txt)

**Comment by samplonius** [comment]
Currently, the the ARP tables are dumped, and the switch database MAC table is dumped, and the IPs and MACs are matched.  If DHCP snooping is enabled, you can just dump that instead of the MAC table.  So, DHCP snooping is basically a new scanning function.

As far as 802.1x, I'm not sure what the goal is.  Include user names and domains with the MAC-IP linkage?

**Comment by jpobeda** [comment]
@samplonius 
It's NOT the same. While you can have lots of MAC on 1 port for example, not necessarily means that all of them have got an entry in dhcp snooping database. That could depend on what vlans are you running dhcp snooping on, or many other factors.

So I think dhcp snooping, could only replace the ARP function and this way you could cross reference between get_mac and get_dhcp_snooping for example.

In my particular case scenario for example, the function get_arp doesn't add much value to me.

Regarding 802.1x the goal is pretty much the same as for the other functions but applied to dot1x.

Username/Domain(data/voice)/Mode/IP/Status

If you're not running ACS/ISE or any other NAC, how do you normally do to track down where user authenticating dot1x is connected to?

**Comment by jpobeda** [comment]
I got the dhcp snooping function working as an IP Scanning Function.
This one was a pain because the MIB isn't fully implemented. You'll see once you look at the code..

I'm also close to get the dot1x finished.

I'd like to ask you to have a look at the code once I pull the request to tidy it up.

**Comment by cigamit** [comment]
Not a problem, though it might be delayed a bit.  Glad you are helping keep MacTrack relevant.

**Comment by jpobeda** [comment]
This https://github.com/Cacti/plugin_mactrack/pull/40 should cover pretty much of it.

**Comment by cigamit** [comment]
I'm going to close based upon your pull request.  You should bump the minor version and update the REAME.md ChangeLog section.
