### ISSUE TITLE
Can't enable Mactrack on Cacti 1.1.2

### ISSUE THREAD

**Issue by emagadan** [Cacti/plugin_mactrack#19]
Hello, I'm setting up Cacti 1.1.2, so far all seems OK. I downloaded the mactrack plugin and installed it on the Cacti/Plugins folder, I can see it on Cacti, I am able to "install" it but when I click on the green check mark to enable it nothing happens. Am I missing something?

Your help support is appreciated

**Comment by jpobeda** [comment]
Have you renamed it to just "mactrack" ?

**Comment by emagadan** [comment]
Javier,

Yes I have, I did it right after I copied the mactrack folder to the plugins folder, then I went to the Cacti interface, I have the same behavior with “thold”. See image below, both appear as installed but I can’t enable them, I have click several times, logout of Cacti, even rebooted the CentOS machine and nothing. 

Nectar and clog came integrated on Cacti 1.1.2. I haven’t tried with the other plugins shown which is why I haven’t renamed the folders just yet.

-Eduardo

**Comment by jpobeda** [comment]
Can't see any image attached.

Have you check file permissions? Selinux? Where did you get mactrack from? github?

**Comment by emagadan** [comment]
Javier,

Yes, I got mactrack from github. Selinux is disabled (see below), I’m attaching the picture again, changed from PNG to JPG, hope you can see it.
[root@localhost ~]# sestatus

SELinux status:                 disabled

[root@localhost ~]#

[root@localhost ~]#

[root@localhost ~]# getenforce

Disabled

[root@localhost ~]#

**Comment by jpobeda** [comment]
Hi,

I still can't see any picture BUT since you are running 1.1.2 have you tried with latest one? I'm not part of the Cacti team so I don't know what else to look at, sorry. It's weird it actually does the "install" but it does not let you enable it.

You could try posting in the cacti forum so someone else that had the same issue could help you out.

**Comment by emagadan** [comment]
Ok, will try running with newer cacti version and see how it goes

Thanks for the effort!

**Comment by cigamit** [comment]
That is the issue.  The plugin management interface incorporates a minimum version, and for the current MacTrack it's 1.1.6 I think.  However, the GUI does not make this obvious.  That's a bug.  You can edit the INFO file and see the required version of Cacti.
