### ISSUE TITLE
Device Types broken after recent update.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#195]
All switches and routers device types not longer work.
Device types still exist and are not disabled.
```
2023/08/11 16:35:48 - MACTRACK WARNING: SITE: TMH, IP: 10.7.24.20, TYPE: Cisco IOS Software, C2900 Software (C290, ERROR: Device Type Not Found in Device Type Table.
2023/08/11 16:35:48 - MACTRACK WARNING: SITE: TMH, IP: 10.9.0.214, TYPE: Cisco IOS Software [Amsterdam], Catalyst, ERROR: Device Type Not Found in Device Type Table.
```

**Comment by TheWitness** [comment]
Likely the are disabled.  Check the most recent updates from @xmacan

**Comment by xmacan** [comment]
Show result of:
select description, disabled from mac_track_device_types;

**Comment by jdcoats** [comment]
```
MariaDB [cacti]> select description, disabled from mac_track_device_types;
+-------------------------+----------+
| description             | disabled |
+-------------------------+----------+
| C2600 Router            |          |
| C2960S Switch           |          |
| C3550 Switch            |          |
| C3750 Switch            |          |
| 45xx Switch             |          |
| 45xx Switch             |          |
| C2900 Router            |          |
| ASR Router              |          |
| 6513 Switch/Router      |          |
| CE500 Switch            |          |
| C2950 Switch            |          |
| C2800 Router            |          |
| BladeCenter2 10G        |          |
| DellBladeCenter         |          |
| VG224                   |          |
| C870 Router             |          |
| Cisco ASA               |          |
| C3x50 Switch            |          |
| C3900 Router            |          |
| Blade Center 10/100     |          |
| CAT4500                 |          |
| C3560 Switch            |          |
| ProCurve Switch         |          |
| CAT3K_CAA-UNIVERSALK9-M |          |
| IBM Flex System Fabric  |          |
| C2960X Switch           |          |
| 2960 Switch Lite        |          |
| 2960 Switch Base        |          |
| VG3X0                   |          |
| 93xx + 94xx Switch      |          |
| 43xx Router             |          |
| Nexus Generic           |          |
| Nexus 7K                |          |
| Nexus 5K                |          |
| 92xx Switch             |          |
| Comware 5130            | on       |
| Aruba 6300              | on       |
| Aruba 6200              | on       |
| Comware 1920            | on       |
| Comware 5140            | on       |
| Aruba 2530 8p           | on       |
| Aruba 2930 8p           | on       |
+-------------------------+----------+
42 rows in set (0.000 sec)
```

**Comment by jdcoats** [comment]
also, the disable switch should be in the actions menu so it can be set in bulk.

**Comment by jdcoats** [comment]
I tried flipping the switch just incase it was working backwards and that didnt help :)

**Comment by xmacan** [comment]
try to run:
php mactrack_scanner.php --debug -id=X
X = id from device tracking -> devices -> choose any and id will be in URL ...action=edit&device_id=X

**Comment by jdcoats** [comment]
```
 # php mactrack_scanner.php --debug -id=154
2023/08/15 08:29:41 - MACTRACK HOST: 10.9.0.223 is alive, processing has begun.
2023/08/15 08:29:41 - MACTRACK WARNING: SITE: TMH, IP: 10.9.0.223, TYPE: Cisco IOS Software, C2960X Software (C29, ERROR: Device Type Not Found in Device Type Table.
```

**Comment by xmacan** [comment]
Device types definition - have you there wildcard % or *?

**Comment by jdcoats** [comment]
no wildcard or special characters

**Comment by xmacan** [comment]
please show me your device type definition for C2960X and snmp information for any C2960X switch (Device tracking->devices->choose any and show top, something like:
SNMP Information
System: HPE Comware Platform Software, Software Version 7.1.070, Release 3506P06 HPE 5130 48G 4SFP+ EI Switch Copyright (c) 2010-2020 Hewlett Packard Enterprise Development LP
Uptime: 172203215
Hostname: 5130
ObjectID: .1.3.6.1.4.1.25506.11.1.186

**Comment by jdcoats** [comment]
```
H-IT-Depot-SW24-01.TMH.ORG (10.9.0.223)
SNMP Information
System: Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(7)E4, RELEASE SOFTWARE (fc2) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2021 by Cisco Systems, Inc. Compiled Mon 08-Mar-21 11:26 by prod_rel_team
Uptime: 2902213094
Hostname: H-IT-Depot-STCK-01
ObjectID: .1.3.6.1.4.1.9.1.1208
```

**Comment by jdcoats** [comment]
![image](https://github.com/Cacti/plugin_mactrack/assets/42470924/c1df77a8-ce5a-4659-8251-a4755a6af13f)

**Comment by xmacan** [comment]
I need detail of C2960X type

**Comment by xmacan** [comment]
@jdcoats please show device type for C2960X

**Comment by jdcoats** [comment]
It is shown 2 posts above in the screenshot

**Comment by xmacan** [comment]
There is only list of all your device types. I cannot see this specific device type

**Comment by jdcoats** [comment]
2960X is in that list. It shows the same detail as this. Im not clear what else you are asking for.

![image](https://github.com/Cacti/plugin_mactrack/assets/42470924/96b3f441-2803-46b2-8048-9f39a34d2b10)

**Comment by xmacan** [comment]
System description match - change C2960X to \*C2960X\*

**Comment by jdcoats** [comment]
oh so the code changed and you do expect a wildcard now for all of the device types if sys desc isnt exact?

**Comment by xmacan** [comment]
Yes, I changed the code. I think that old code was wrong. Match means that it is equal. 
In your case "C2960X" **not equal to** "Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(7)E4, RELEASE SOFTWARE (fc2)".
I use the same logic as is for Vendor SNMP Object ID Match

**Comment by jdcoats** [comment]
okay, I'll fix this up then :)

**Comment by jdcoats** [comment]
Maybe add a note that the basic functionality of the plugin has changed and make it so people see it? Its a simple enough change but .....

**Comment by xmacan** [comment]
I would like add more "prepared" device types to new version. It seems that you have more records then me. would you be willing to send them to me? Ideally mysqldump of table mac_track_device_types.

Documentation is mactrack's big pain :-(

**Comment by jdcoats** [comment]
[mac_track_device_types.zip](https://github.com/Cacti/plugin_mactrack/files/12359434/mac_track_device_types.zip)

**Comment by xmacan** [comment]
Thank you. So we can close this now?

**Comment by jdcoats** [comment]
same problem even with wildcards. Is it that "I use the same logic as is for Vendor SNMP Object ID Match" and before if nothing was there then it mean any and now without one specified it doesn't work? Do you expect a * for SNMP Object ID also?

**Comment by jdcoats** [comment]
no that doesn't work either
```
 # php mactrack_scanner.php --debug -id=154
2023/08/16 17:17:43 - MACTRACK HOST: 10.9.0.223 is alive, processing has begun.
2023/08/16 17:17:43 - MACTRACK WARNING: SITE: TMH, IP: 10.9.0.223, TYPE: Cisco IOS Software, C2960X Software (C29, ERROR: Device Type Not Found in Device Type Table.
```
![image](https://github.com/Cacti/plugin_mactrack/assets/42470924/4a3e6b6f-0489-45a7-84b0-fc80b778b2b9)

**Comment by xmacan** [comment]
I have found a problem. Wait i minute

**Comment by jdcoats** [comment]
It works now :) Thanks.

**Comment by xmacan** [comment]
Great, closing

**Comment by jdcoats** [comment]
I spoke to soon. I guess this issue with the device types is fixed but the scanning function never completes.
```
2023/08/17 08:57:25 - SYSTEM MACTRACK STATS: Time:14340.2181 ConcurrentProcesses:10 Devices:230
2023/08/17 08:57:25 - CMDPHP ERROR: Device Tracking timed out during main script processing.
```

**Comment by xmacan** [comment]
try again only one device:
php mactrack_scanner.php --debug -id=154
Is it correct?

Have you got SYSTEM MACTRACK STATS before mactrack update? How was the time?

**Comment by jdcoats** [comment]
i just cleaned up a bunch of abended resolver processes and re-ran in debug mode it is working, no more devices in error state

**Comment by jdcoats** [comment]
Thanks, this is resolved.
