### ISSUE TITLE
mactrack: ERROR: Device Type Not Found in Device Type Table.

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_mactrack#20]
Hey!
I'm using mactrack 0.3 on Ubuntu 16.04 with cacti version 0.8.8f and everything is working fine with my Cisco catalyst switches.
I have a parallel cacti system with cacti version 1.1.13 and mactrack 4.0 on Ubuntu 17.04.
I made the same settings. Here my settings:
![mactrack1](https://user-images.githubusercontent.com/28043745/28615009-fb2739c4-71f7-11e7-8e55-57d9a94b4220.JPG)
![mactrack2](https://user-images.githubusercontent.com/28043745/28615007-fb1a5a6a-71f7-11e7-8e13-915f1c04eed6.JPG)
![mactrack3](https://user-images.githubusercontent.com/28043745/28615008-fb1ee4ae-71f7-11e7-8622-ad6d8ee6bd26.JPG)
But the device type is unknown.
Can someone help me?

**Comment by cigamit** [comment]
Th e OID match must be numeric.
