### ISSUE TITLE
Command line does’t work [4.7]

### ISSUE THREAD

**Issue by xxconn** [Cacti/plugin_mactrack#215]
When I run MacTrack at the command line mode, it will show the error message with ‘the function plugin_mactrack_version not defined.’

Does anyone know how to run Mactrack at the command line?

**Comment by xmacan** [comment]
please show how did you run it and complete output with error

**Comment by xxconn** [comment]
Here is my output

![01](https://github.com/Cacti/plugin_mactrack/assets/170719817/5507abcd-370d-4b3f-9b12-02ed9955faf0)

**Comment by xxconn** [comment]
Done.  My fault environment.
