### ISSUE TITLE
Add more mac address formats

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_mactrack#228]
add mac address formats:
xxxx-xxxx-xxxx
xxxx.xxxx.xxxx
xxxxxxxxxxxx 

1) change settings "Mac address delimiter" to "Mac address format"
2) prepare function mt_format_mac
3) use everywhere

(https://github.com/Cacti/cacti/discussions/5746)

**Comment by TheWitness** [comment]
Maybe make the is user preference.  It's already there but missing the - as an option.

**Comment by xxconn** [comment]
xxxx-xxxx-xxxx
xxxx.xxxx.xxxx
xxxxxxxxxxxx
xx:xx:xx:xx:xx:xx

What is the format of MAC's data in the database?
If it's a user preference, it means that is the display format.

**Comment by TheWitness** [comment]
The later.  Those other two formats are not supported, but are only a code change away.

**Comment by xxconn** [comment]
Add one more format:
xx-xx-xx-xx-xx-xx

**Comment by TheWitness** [comment]
That format and the colon format are both supported.  I think they are stored in the database with colons, but it’s honestly been so many years since I wrote it, I don’t remember 😉
