### ISSUE TITLE
Deleting sites does not work properly

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#25]
Hi there,

I wonder if any of the cacti guys can have a look at this one.

![2017-08-25_14-39-19](https://user-images.githubusercontent.com/13456559/29697471-7b96acee-89a3-11e7-8f0c-628e72dfc1ed.gif)

The blank page every time the action finishes makes me crazy btw.

**Comment by cigamit** [comment]
Is this fixed now?

**Comment by jpobeda** [comment]
Nope, can you help with this one?

**Comment by cigamit** [comment]
Resolved.
