### ISSUE TITLE
Macktrack view_graphs does NOT work

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#26]
This tab is not currently working as I think it suppose to work.

When you are navigating view_devices and click on show graphs for X device it does work because the URL is formatted on mactrack_view_devices.php and you get the graphs filtered by the device you have selected.

There was a typo in mactrack_view_devices.php for that so I fixed it. 
This commit: https://github.com/Cacti/plugin_mactrack/pull/24/commits/8b0ed3febab9f00331729bf09eecfe1d36b73161

Now coming to the view_graphs stuff, when you go to the tab, you get the "Report view" where you are suppose to be able to filter by devices, date/time, etc.

Once you are there, it sort of filters the graph preview according to the mactrack devices, but then, you can move to the next pages for example.
[EDIT]Moving through pages actually works if you do an F5 there[/EDIT]

You can't filter by device in that page.

You can't search any string, it just simply does nothing.

The timespan presets and device template filters work fine.

**Comment by cigamit** [comment]
Did you fix this?

**Comment by jpobeda** [comment]
Nope, To be honest, I've never used MacTrack before so I don't know what to expect on this TAB. It looks like you should be able to select graphs from the list and display them but that wouldn't add any real value because are the same graphs I could see on Cacti's tree

**Comment by jpobeda** [comment]
I'm closing this one, because I'm not particularly interested on this.

I think It would be much helpful display the graphs on mouse hover or something like that.
