### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#29]
Hi there, just testing translations found several issues. Lots of them are common to multiple forms.

If any of the Cacti Group could help with some of these I'll try to pick up the logic and push PRs to fix them. I can't guarantee though.

![chrome_2017-09-05_14-57-16](https://user-images.githubusercontent.com/13456559/30043577-4f3dfc54-924c-11e7-9ed5-e7471a0854de.png)
![chrome_2017-09-05_14-54-14](https://user-images.githubusercontent.com/13456559/30043580-4f513602-924c-11e7-8bb5-9fbc064d9341.png)
![chrome_2017-09-05_14-54-28](https://user-images.githubusercontent.com/13456559/30043578-4f3f9e7e-924c-11e7-9445-597ae6852701.png)
![chrome_2017-09-05_14-54-34](https://user-images.githubusercontent.com/13456559/30043579-4f3fb3c8-924c-11e7-8cfd-116099a56918.png)
![chrome_2017-09-05_14-54-44](https://user-images.githubusercontent.com/13456559/30043582-4f60dfc6-924c-11e7-9c7a-37226d0cf7b3.png)
![chrome_2017-09-05_14-54-59](https://user-images.githubusercontent.com/13456559/30043581-4f51f740-924c-11e7-9739-6f9f5e4fdba5.png)
![chrome_2017-09-05_14-55-11](https://user-images.githubusercontent.com/13456559/30043583-4f6812b4-924c-11e7-8bfc-7c53a7b964ee.png)
![chrome_2017-09-05_14-55-21](https://user-images.githubusercontent.com/13456559/30043584-4f6919f2-924c-11e7-99e8-dfa5272b0196.png)
![chrome_2017-09-05_14-56-05](https://user-images.githubusercontent.com/13456559/30043585-4f6a09de-924c-11e7-9a04-796ea35d6f3a.png)
![chrome_2017-09-05_14-56-15](https://user-images.githubusercontent.com/13456559/30043586-4f7a5cd0-924c-11e7-97b3-17e3718afdc7.png)
![chrome_2017-09-05_14-56-32](https://user-images.githubusercontent.com/13456559/30043587-4f7cae54-924c-11e7-8fba-1c55d6001931.png)
![chrome_2017-09-05_14-56-45](https://user-images.githubusercontent.com/13456559/30043588-4f8a8d12-924c-11e7-9420-91b80672a3ec.png)
![chrome_2017-09-05_14-56-52](https://user-images.githubusercontent.com/13456559/30043589-4f928396-924c-11e7-9da2-e9a2ab0b79b5.png)
![chrome_2017-09-05_14-57-08](https://user-images.githubusercontent.com/13456559/30043590-4f931e78-924c-11e7-9b3a-4b2649d3e6bc.png)

**Comment by cigamit** [comment]
You should be all set now.  Was a pretty 'huge' change.  So, you will need to do some testing too.  Should be reasonably solid though.

**Comment by cigamit** [comment]
Open up a new issue if you find anything after you changes.
