### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#31]
Hi there,

Huge progress after that commit. Let's if we can sort these ones out.

![chrome_2017-09-07_15-47-33](https://user-images.githubusercontent.com/13456559/30145899-cceb7440-93e8-11e7-8c0e-79dfd3be63ff.png)
![chrome_2017-09-07_15-47-49](https://user-images.githubusercontent.com/13456559/30145903-cd005842-93e8-11e7-9ec6-5120d622eb9d.png)
![chrome_2017-09-07_16-00-32](https://user-images.githubusercontent.com/13456559/30145902-ccf108ce-93e8-11e7-9a67-11c7af702f0f.png)
![chrome_2017-09-07_16-01-05](https://user-images.githubusercontent.com/13456559/30145900-ccedc6e6-93e8-11e7-8c32-698aa2b588a3.png)
![chrome_2017-09-07_16-01-25](https://user-images.githubusercontent.com/13456559/30145901-ccf00b54-93e8-11e7-9c66-b4a7b9414ee9.png)

Cheers

**Comment by cigamit** [comment]
I see a number of these string all handled.  Did you run the update-pot.sh file first?  I did correct the one spelling error just a few minutes ago.

**Comment by jpobeda** [comment]
No, I didn't. I'll check it now.

**Comment by jpobeda** [comment]
Oh man, you screw my day hahahaha
200 entries to fix...Let's close this.

Thanks for you help :D
