### ISSUE TITLE
[Q]There is already one in progress

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#34]
Hi there,

> Cacti version 1.1.17
> Mactrack latest from github

Since I compiled and changed my poller to spine I started to get this error.

> MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress

When MacTrack is running, it only runs 1 poller process but multiples mactrack_scanners (Max is set to 7).
Max per device scan time is set to 20.

The function that is triggering the error is querying the following:
I'm a bit confused because it supposes to get there if I'm running this from cli which is not the case.
So, of course that it will find other processes when the poller is running. 

> 
> select * from mac_track_processes;
> +-----------+------------+---------+---------------------+
> | device_id | process_id | status  | start_date          |
> +-----------+------------+---------+---------------------+
> |        -1 |          0 | Running | 2017-09-12 11:35:51 |
> |        24 |      26921 | Running | 2017-09-12 11:36:06 |
> |        38 |      27013 | Running | 2017-09-12 11:36:10 |
> |        40 |      27009 | Running | 2017-09-12 11:36:10 |
> |        41 |      27007 | Running | 2017-09-12 11:36:10 |
> |        42 |      27017 | Running | 2017-09-12 11:36:10 |
> +-----------+------------+---------+---------------------+

> SELECT count(*) FROM mac_track_processes;
> +----------+
> | count(*) |
> +----------+
> |        3 |
> +----------+

I thought I might have introduced a bug with my latest commits but I reverted them back just in case.

Keeps happening.

**Comment by jpobeda** [comment]
Oh crap...I've just realized that I've also changed the poller interval to 1min.


I'm not sure how it works but I'm guessing cacti's poller calls mactrack's poller?

**Comment by cigamit** [comment]
Correct, MacTrack and the other plugin processes are launched by the main poller.php process.  As a naming convention, and we are pretty good about this, all files labled 'poller_*.php' are launched by the main data collector.

Additionally, MacTrack data collection can take a little while.  Best to reduce the frequency.

**Comment by cigamit** [comment]
Should be better now, but not perfect in my opinion.
