### ISSUE TITLE
[Help]Cosmetic Issue @Dot1x TAB

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#41]
Hi Jimmy,

I know you're busy and there is no rush but when you get some spare time to look at this, I'd appreciate it.

In the first screenshot you can see that "Status" shows the code numbers

![chrome_2017-11-13_12-23-12](https://user-images.githubusercontent.com/13456559/32704661-8dc30864-c86d-11e7-889c-36d9d4ab6df6.png)

I'd like to make it the references like the 2nd screenshot

![chrome_2017-11-13_12-24-41](https://user-images.githubusercontent.com/13456559/32704672-b34dc970-c86d-11e7-8848-8237b1d07bcd.png)

I gave it a few tries but I broke it every time :(

**Comment by jpobeda** [comment]
@netniV 

Can you help me to sort this out?

**Comment by netniV** [comment]
Sure, I'll take a look tomorrow.  Just give me the two locations (pages) as I haven't used the mactrack at all yet :)

**Comment by netniV** [comment]
Never mind, give this a try and see if it works for you.

**Comment by jpobeda** [comment]
mmm I still see the numbers instead

**Comment by jpobeda** [comment]
![image](https://user-images.githubusercontent.com/13456559/35076884-6b4992d2-fc5f-11e7-9c40-fe4fc7f8d092.png)

**Comment by netniV** [comment]
Updated, this was a Layer 8 issue 👍

**Comment by netniV** [comment]
Have you had a chance to try it out yet @jpobeda ?

**Comment by jpobeda** [comment]
Yes, sorry. I'm in NZ it's 8.32 AM hahaha

I wrote a comment on your PR.

**Comment by jpobeda** [comment]
Fixed by https://github.com/Cacti/plugin_mactrack/commit/b2a0be5204636e06a817f79ac1673f0ca4f4d734

Thanks @netniV
