### ISSUE TITLE
[Help]Mactrack data retention

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#42]
I need some help here to apply the data retention clean up to mac_track_dot1x tables as well.

It gets quite populated and some queries can get a bit slow with too many results.

I looked at the function but I couldn't figure it out.

Any help here would be appreciated as well. I'm logging a separated issue just to keep it tidy.

I also added an ifIndex INDEX to table mac_track_interfaces on my database and I didn't put that into the setup.php. I'm not sure how you handle that, should it go to the create statement and to the upgrade as well? I've got the patch ready to PR. I just wanted to double check it with you.

Please advise.

**Comment by netniV** [comment]
Hi @jpobeda, what status is this in?

**Comment by jpobeda** [comment]
Haven't done a single bit.
Last time I looked at that function drove me crazy so I dropped it, hoping someone would help.
In the meantime I flush the record every now then.

Unfortunately I won't have time until July/August IF I'm lucky.

This is something that needs to be addresses otherwise the database will get loaded with lots of records. So I'd keep this open as a reminder at the very least.

**Comment by netniV** [comment]
What did you do as a flush?

**Comment by jpobeda** [comment]
I'm making use of the "Remove All Scan Results" function under Tracking Tools/Tracking Utilities

Under settings there is a "Data Retention" option. I've got that pretty low (3 days) but I was expecting to make the dot1x data part of this function so we can keep it consistent.

`function perform_mactrack_db_maint()`

When I wrote the 802.1x thing I found and looked at that bloody function but it drove me crazy so instead of screwing it I decided to leave it to a proper dev =D

**Comment by netniV** [comment]
So basically, per device you want it to remove scan results that are beyond the retention level?

**Comment by jpobeda** [comment]
Yep, I think we should be cleaning those records at the same time `function perform_mactrack_db_maint()` cleans up all the other ones.

I don't know if there would be any use on cleaning those records separated from the rest because that could also break some JOIN queries, etc.

Don't you think?

**Comment by cigamit** [comment]
If you are using the 802.1x stuff, I think there is a full outer join in the code, which would wreck your database. Ensure that you are not using it.  We should implement partitioning for the ports tables, which the mactrack_convert.php script will do.  You should review that and implement partitioning using InnoDB.

If you are using 802.1x, I need someone to test the fixes.  I don't have any of this stuff running, but I did see the join.  Just don't have the details any more.

**Comment by JorisFRST** [comment]
Hi,
I am just setting up this functionality at a new site. so have plenty of time to test if someone wants to help out.

**Comment by jpobeda** [comment]
@JorisFRST make sure you keep an eye on those records, at that time I couldn't quite understand how the data retention function worked to add the dot1x stuff so it doesn't get cleaned up.

What I do from time to time is delete all records and let it start over..ugly workaround I know.

**Comment by TheWitness** [comment]
We need to implement partitioning at some point.  Having worked on a MacTrack setup some 15+ years ago with 30+ sites and over 3500 switches, routers and hubs, I know what can happen with the Database.  If think some of the performance issue are "better" now on the dot1x mappings, so I'm going to close this one.  I think that some of the partitioning stuff was actually merged into the code, but it looks like Jimmy did not finish implementing.
