### ISSUE TITLE
Add Wiki _sidebar

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#43]
* I created a couple of wiki pages for those wondering how to mt up.

* I don't seem able to create a _sidebar though and also can't add the footer. 

* If it's fine for you I can create a directory under docs for the screenshots. They are currently on 1 of my forks.

If you want to create it, this is the code.

```
[Main](https://github.com/cacti/plugin_mactrack/wiki)

[Installation](https://github.com/cacti/plugin_mactrack/wiki/Installation)

  * [Setup](https://github.com/cacti/plugin_mactrack/wiki/Setting-Device-Tracking-up)
  
    * [Device Types](https://github.com/cacti/plugin_mactrack/wiki/Defining-Device-Types#device-types)
    * [Add Device Type](https://github.com/cacti/plugin_mactrack/wiki/Add-Device-Type)
    * [Add Sites](https://github.com/cacti/plugin_mactrack/wiki/Add-sites)
    * [Import OUI DB](https://github.com/cacti/plugin_mactrack/wiki/Import-OUI-Database)
    * [SNMP Set Options](https://github.com/cacti/plugin_mactrack/wiki/SNMP-Set-Options)
 * [Troubleshooting](https://github.com/cacti/plugin_mactrack/wiki/Troubleshooting)
```

**Comment by jpobeda** [comment]
@cigamit have you had the time to look at this? Is this something you may want to do in a different way?

**Comment by cigamit** [comment]
Can you do it in a pull request?

**Comment by jpobeda** [comment]
@cigamit, I didn't know that was something doable from PR, can you point me in the right direction?

If you now go to Wiki now, you should see the pages I have already created under Cacti/plugin_mactrack. Somehow I was allowed to do it, but I'm not allowed to create the sidebar menu.

**Comment by jpobeda** [comment]
I'd do a PR for the screenshots, but other than that..

**Comment by cigamit** [comment]
Bah, my bad.  Now I know what you are talking about.  Give me a few minutes.  Looking at it now.

**Comment by cigamit** [comment]
I just cut and pasted.  Is that what you were looking for?

**Comment by jpobeda** [comment]
@cigamit, Yes, awesome, It does now let me edit it, so I'm closing this one and I'll be creating a PR for the screenshots.

Under docs/images it's fine for you?

**Comment by netniV** [comment]
I was going to say that I just looked at the Wiki and it seems to be using local images from your own repo.
