### ISSUE TITLE
Manually choose trunk ports

### ISSUE THREAD

**Issue by jdmsilbvs** [Cacti/plugin_mactrack#46]
Is it possible to add a field in order to manually choose which ports are trunk ?

**Comment by cigamit** [comment]
Generally, the 'Ports to Ignore' field was used to force removing known trunks from the mac association.

**Comment by jpobeda** [comment]
It's now also auto-detect as far as I remember from the last time I've looked at that function.

The question is a little bit of ambiguous. 

Can you please specify what is what you want to achieve?

**Comment by netniV** [comment]
No further input received.  Closing.

**Comment by JorisFRST** [comment]
Hi,
in my opinion the auto function works very well.

But there are cases where you want to track the macs learned over a trunk also. (wireless, virtual hosts , ... "
So if we can have an "override automatic trunk detection" for certain ports in addition to the "ports to ignore" option that would be good.

**Comment by xxconn** [comment]
PR #221 added this enhancement
