### ISSUE TITLE
ERROR mactrack_scanner.php: get_dlink_l2_switch_ports

### ISSUE THREAD

**Issue by Cramin** [Cacti/plugin_mactrack#49]
Hello
I have a lot of errors in cacti log. 

> 2018/01/12 17:23:48 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_scanner.php: 167 get_dlink_l2_switch_ports)(/plugins/mactrack/lib/mactrack_dlink.php: 56 CactiErrorHandler)(/lib/functions.php: 4434 cacti_debug_backtrace)
> 2018/01/12 17:23:48 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined offset: 2022 in file: /var/www/html/plugins/mactrack/lib/mactrack_dlink.php on line: 56

I have DLink L3 switches DES-3828 and DES-3852.
Cacti 1.1.30 PHP 7.0.27 MariaDB 10.1.26 Debian 9.3

**Comment by netniV** [comment]
Can you get me the SNMP walk of your dlink?  If you want to sent it privately, use my hotmail.com address.

**Comment by netniV** [comment]
No response, closing this issue.
