### ISSUE TITLE
How to disable "802.1x Scanning Function"

### ISSUE THREAD

**Issue by Cramin** [Cacti/plugin_mactrack#50]
I have a lot of warnings in log for non 802.1x devices. How can i disable this for non 802.1x device types.

> 2018/01/13 13:21:02 - CMDPHP WARNING: SNMP Error:'snmp2_real_walk(): Error in packet at '.1.3.6.1.4.1.9.9.656.1.4.1.1.10': No Such Object available on this agent at this OID', Device:'10.100.202.146', OID:'.1.3.6.1.4.1.9.9.656.1.4.1.1.10'
--
> 2018/01/13 13:21:02 - CMDPHP WARNING: SNMP Error:'snmp2_real_walk(): Error in packet at '.1.3.6.1.2.1.3.1.1.1': No Such Object available on this agent at this OID', Device:'10.100.202.146', OID:'.1.3.6.1.2.1.3.1.1.1'

Thanks
Sorry for my english.

**Comment by jpobeda** [comment]
Find that device type and change Dot1x Scanning to not Applicable. Is this a new fresh install or you've upgraded existing one?

**Comment by Cramin** [comment]
This is upgraded Cacti from 1.0.6 to current. MacTrack is installed two days ago from github.
[https://i.imgur.com/erI5CQF.png](url)

**Comment by jpobeda** [comment]
mmm That's odd. 

Can you please go to Tracking tools menu and under Tracking Utilities click on "Refresh Scanning Functions" and see if then you can select "Not applicable" ?

**Comment by Cramin** [comment]
Thanks, its solved the problem.
I changed to Not applicable.

**Comment by Cramin** [comment]
> 2018/01/16 14:54:14 - CMDPHP WARNING: SNMP Error:'snmp2_real_walk(): Error in packet at '.1.3.6.1.2.1.3.1.1.1': No Such Object available on this agent at this OID', Device:'10.100.202.164', OID:'.1.3.6.1.2.1.3.1.1.1'
> 2018/01/16 14:54:14 - MACTRACK WARNING: SITE: Bloki Myszków, IP: 10.100.202.162, TYPE: DES-3828 Fast-Ethernet Switch, ERROR: 802.1x Address Scanning Function Does Not Exist.

I was happy to fast. Problem is not solved.

**Comment by cigamit** [comment]
Do those log messages include a backtrace?

**Comment by Cramin** [comment]
Only Errors and Warnings like above.

**Comment by jpobeda** [comment]
I'm not sure about this but after you did the "refresh scanning functions" did you also remove all the scanning results?

The 1.3.6.1.2.1.3.1.1.1 OID is part of "get_standard_arp_table" function so it has nothing to do with 802.1x

It might be something kept in the database from the time before you refreshed the scanning functions as well.

I've got a couple of device types that do not run 802.1x without any of these warnings.

**Comment by Cramin** [comment]
I deleted everything, removed devices and add them again to mactrack.
Maybe devices are not fully supported.

**Comment by jpobeda** [comment]
I can't reproduce it myself. I only manage Cisco devices here.

The 802.1x function at the moment is only for Cisco devices that is why is part of the mactrack_cisco.php and not a global function.

Can you please run the following from command line?

php -q mactrack_scanner.php -id='id of one of these devices" -d

If there is sensitive data, please remove it. I'd like to see what's going on.

Also
```
mysql -u cacti_username -p
use cacti_database;
select * from mac_track_device_types;
```

I'll have a look at the mactrack_dlink.php file and see if spot something. 

Since I remember to have introduced a new scanning function type maybe the other functions are checking something like > 1 or similar that could be matching this new type id (3)...

In the meantime you may want to download this version, which is prior to dot1x function and see how it goes.
https://github.com/Cacti/plugin_mactrack/tree/81ef4b3949d57e5cf637ec627e5caef52025cb92

Maybe we should ask @cigamit to cut a few releases, 1 prior to dot1x and 1 after so people don't get stuck there.

**Comment by Cramin** [comment]
When dot1x enabled in device type, i get warnings in log but mactrack is working and collect data.
https://pastebin.com/3axehAAP
When i set Not Applicable in Device Type and i get errors in log, mactrack is not collecting data.
https://pastebin.com/qtqNtiEc
And mysql:
https://pastebin.com/9VayFvBd

**Comment by jpobeda** [comment]
Something is wrong, if you set "Not applicable" instead of "get_cisco_dot1x_table" the MySQL query should show that instead. But in your query I see "get_cisco_dot1x_table".

And please in the future, make use of github quotes, code labels, etc. Just paste the results and use the formatting options

![image](https://user-images.githubusercontent.com/13456559/35121415-30d1f990-fd00-11e7-9492-367a396098d8.png)

To be clear, I want the mysql query when device_type is set to "Not Applicable".

This is mine for eg:
```
+----------------+-------------+--------+-------------+----------------+-------------------+------------------------------------+------------------------------+-------------------------+------------------------+---------+----------+
| device_type_id | description | vendor | device_type | sysDescr_match | sysObjectID_match | scanning_function                  | ip_scanning_function         | dot1x_scanning_function | serial_number_oid      | lowPort | highPort |
+----------------+-------------+--------+-------------+----------------+-------------------+------------------------------------+------------------------------+-------------------------+------------------------+---------+----------+
|              2 | CAT 2900XL  | Cisco  | 1           | C2900          | .1.3.6.1.4.1.9    | get_catalyst_dot1dTpFdbEntry_ports | Not Applicable - Switch/Hub  | Not Applicable          | 1.3.6.1.4.1.9.5.1.2.19 |       0 |        0 |
|              1 | CAT 2950    | Cisco  | 1           | C2950          | .1.3.6.1.4.1.9    | get_IOS_dot1dTpFdbEntry_ports      | Not Applicable - Switch/Hub  | Not Applicable          | 1.3.6.1.4.1.9.5.1.2.19 |       0 |        0 |
|              3 | CAT 2960    | Cisco  | 2           | C2960          | .1.3.6.1.4.1.9    | get_IOS_dot1dTpFdbEntry_ports      | get_cisco_dhcpsnooping_table | get_cisco_dot1x_table   | 1.3.6.1.4.1.9.5.1.2.19 |       0 |        0 |
|              4 | CAT 3750    | Cisco  | 2           | C3750          | .1.3.6.1.4.1.9    | get_IOS_dot1dTpFdbEntry_ports      | get_cisco_dhcpsnooping_table | get_cisco_dot1x_table   | 1.3.6.1.4.1.9.5.1.2.19 |       0 |        0 |
+----------------+-------------+--------+-------------+----------------+-------------------+------------------------------------+------------------------------+-------------------------+------------------------+---------+----------+

```

**Comment by jpobeda** [comment]
Without deleting everything, you could create a new device type with the same options you've got and 802.1x set to not applicable and just run the mysql query and post it. Then you can get rid of it.

**Comment by TheWitness** [comment]
Did I actually write this thing?  Maybe, once in a different phase of my life.  You know, when we still were deploying hubs. ;)

**Comment by TheWitness** [comment]
No, this is not a phoenix rising, just letting you guys know I'm still alive :)

**Comment by Cramin** [comment]
```
INSERT INTO `mac_track_device_types` (`device_type_id`, `description`, `vendor`, `device_type`, `sysDescr_match`, `sysObjectID_match`, `scanning_function`, `ip_scanning_function`, `dot1x_scanning_function`, `serial_number_oid`, `lowPort`, `highPort`) VALUES
(1,	'DES-3828 Fast-Ethernet Switch',	'DLink',	'2',	'DES-3828 Fast-Ethern',	'.1.3.6.1.4.1.171.10.69.1',	'get_dlink_l2_switch_ports',	'get_standard_arp_table',	'Not Applicable',	'',	0,	28),
(2,	'DES-3852 Fast-Ethernet Switch',	'Dlink',	'2',	'DES-3852 Fast-Ethern',	'.1.3.6.1.4.1.171.10.69.4',	'get_dlink_l2_switch_ports',	'get_standard_arp_table',	'Not Applicable',	'',	0,	52);
```
And i get multiple Errors and warnings :
```
MACTRACK WARNING: SITE: Szkielet Myszkow, IP: 172.24.208.128, TYPE: DGS-3324SR Stackable Ethernet Switch, ERROR: 802.1x Address Scanning Function Does Not Exist.
CMDPHP WARNING: SNMP Error:'snmp2_real_walk(): Error in packet at '.1.3.6.1.2.1.3.1.1.1': No Such Object available on this agent at this OID', Device:'172.24.208.128', OID:'.1.3.6.1.2.1.3.1.1.1'
```

When change to `get_cisco_dot1x_table` i get multiple warnings like this:

```
01/24/2018 08:34:38 - CMDPHP WARNING: SNMP Error:'snmp2_real_walk(): Error in packet at '.1.3.6.1.2.1.3.1.1.1': No Such Object available on this agent at this OID', Device:'172.24.208.128', OID:'.1.3.6.1.2.1.3.1.1.1'
01/24/2018 08:34:33 - CMDPHP WARNING: SNMP Error:'snmp2_real_walk(): Error in packet at '.1.3.6.1.4.1.9.9.656.1.4.1.1.10': No Such Object available on this agent at this OID', Device:'172.24.208.134', OID:'.1.3.6.1.4.1.9.9.656.1.4.1.1.10'
01/24/2018 08:34:30 - CMDPHP WARNING: SNMP Error:'snmp2_real_walk(): Error in packet at '.1.3.6.1.2.1.3.1.1.1': No Such Object available on this agent at this OID', Device:'172.24.208.129', OID:'.1.3.6.1.2.1.3.1.1.1'
```

**Comment by netniV** [comment]
That error appears because you have something defined in the column `dot1x_scanning_function` and mactrack is trying to find that function.  In your case, this is ''Not Applicable' which should actually be blank.

**Comment by Cramin** [comment]
Are you sure? Look at https://github.com/Cacti/plugin_mactrack/issues/50#issuecomment-358781515 above and his output.

**Comment by netniV** [comment]
If your device type matches those first two lines, that would be correct.  However, you have set both these switches as device type 2 which means it expects a value to be valid in that column from what I can see.

**Comment by cigamit** [comment]
Resolved.

**Comment by cigamit** [comment]
Close if you can confirm.

**Comment by netniV** [comment]
If I read your fix correctly, that was for the ip_scanning column, whereas this issue was over the dot1x column.  Because the example had 'Not Applicable' that was being set in the function column it was trying to find a function called 'Not Applicable'.  I am wondering if an extra function that does the isset, !='' and !='Not Applicable' would be the best fix for all those function columns as a precaution.

**Comment by cigamit** [comment]
Not applicable.  Let me check the GUI.

**Comment by cigamit** [comment]
Oh, that is bad code.  Let me fix it.

**Comment by Cramin** [comment]
New server Cacti 1.1.34 + mactrack develop. Everything working. Thanks.
