### ISSUE TITLE
CMDPHP ERROR: A DB Exec Failed!, Error: Column 'scan_date' cannot be null

### ISSUE THREAD

**Issue by Cramin** [Cacti/plugin_mactrack#53]
```
01/24/2018 08:28:00 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'scan_date' cannot be null
01/24/2018 08:28:00 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO mac_track_ips (site_id,device_id,hostname,device_name,port_number, mac_address,ip_address,scan_date) VALUES (1,1,'172.24.208.128','dgs1.dlink.myszkow','5189','FF:FF:FF:FF:FF:FF','10.100.240.255',NULL)'
```

Lastest Mactrack.

**Comment by Cramin** [comment]
```
SET NAMES utf8mb4;

INSERT INTO `settings` (`name`, `value`) VALUES
('mt_scan_date',	'2018-01-11 00:00:00');
```
There are no `mt_scan_date` table in database. Copied from older Cacti server,

**Comment by netniV** [comment]
That would be correct, you are applying a setting there, not a table. Do a `SHOW CREATE TABLE mac_track_ips \G` for the first error.

**Comment by Cramin** [comment]
```
MariaDB [cacti]> SHOW CREATE TABLE mac_track_ips \G
*************************** 1. row ***************************
       Table: mac_track_ips
Create Table: CREATE TABLE `mac_track_ips` (
  `site_id` int(10) unsigned NOT NULL DEFAULT '0',
  `device_id` int(10) unsigned NOT NULL DEFAULT '0',
  `hostname` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `device_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `port_number` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `mac_address` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `ip_address` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `dns_hostname` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `scan_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`scan_date`,`ip_address`,`mac_address`,`site_id`),
  KEY `ip` (`ip_address`),
  KEY `port_number` (`port_number`),
  KEY `mac` (`mac_address`),
  KEY `device_id` (`device_id`),
  KEY `site_id` (`site_id`),
  KEY `hostname` (`hostname`),
  KEY `scan_date` (`scan_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
1 row in set (0.00 sec)
```

**Comment by netniV** [comment]
OK, so yeah the error is quite correct.  The `scan_date` column expects that you will be providing a date when inserting into the table.  Whilst there is a default value, that value would not be valid in SQL strict mode (to check that run `SELECT @@GLOBAL.sql_mode global, @@SESSION.sql_mode session`).

There should be a backtrace for the code that is generating that error.

**Comment by Cramin** [comment]
428 line in `/var/www/html/plugins/mactrack/lib/mactrack_functions.php`

**Comment by netniV** [comment]
There could be a problem with this bit of code in poller_mactrack.php:
```
        /* save the scan date information */
        if ($site_id == '') {
                $scan_date = date('Y-m-d H:i:s');
                db_execute_prepared("REPLACE INTO settings
                        (name, value) VALUES
                        ('mt_scan_date', ?)",
                        array($scan_date));
        }
```

Especially given that the very next piece of code checks that id slightly differently

```
        if ($site_id > 0) {
                $device_ids = db_fetch_assoc_prepared('SELECT device_id
                        FROM mac_track_devices
                        WHERE site_id = ?
                        AND disabled=""',
                        array($site_id));
```
The function header also makes me think this might be your issue given what it defaults the site_id to:
```
function collect_mactrack_data($start, $site_id = 0) {
```
When you get these errors, does the mt_scan_date row of `settings` change in the DB?

**Comment by netniV** [comment]
Oh and do you have the full backtrace ? Whilst I traced it to that one line, it's useful to know the steps that led to the problem.

**Comment by cigamit** [comment]
Sorry, that was not the first.  netniV, you are on the right track.  I will correct the short term issue of the $scan_date being unset, but if you might track down the larger issue of why the site_id was not properly set, that would be good.

Let me know if this issue is resolved now.

**Comment by netniV** [comment]
I think $site_id was properly set.  I think it was a zero, hence the `$site_id ==''` wouldn't work since it wasn't a string it was a zero. The function seems to deal with it as a numeric everywhere else but that place so I think your fix will work.

**Comment by cigamit** [comment]
Sorry, I have to get in touch algorithmically again.

**Comment by cigamit** [comment]
Can someone test my latest change and report back.

**Comment by jpobeda** [comment]
@cramin maybe? I can't reproduce this.

**Comment by Cramin** [comment]
I have new server, Cacti 1.1.34 + mactrack develop. No error like this.
