### ISSUE TITLE
Issues in mactrack_resolver.php

### ISSUE THREAD

**Issue by kubix42** [Cacti/plugin_mactrack#54]
The variable $site_id is interpreted as a string and not as a variable.
Error in Cacti Log:
01/25/2018 11:31:09 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column '$site_id' in 'where clause'
01/25/2018 11:31:09 - CMDPHP SQL Backtrace: (/plugins/mactrack/mactrack_resolver.php: 130 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
01/25/2018 11:31:12 - DBCALL ERROR: SQL Assoc Failed!, Error:1054, SQL:'SELECT last_rundate, COUNT(last_rundate) AS devices FROM mac_track_devices WHERE disabled = '' AND site_id=$site_id GROUP BY last_rundate ORDER BY last_rundate DESC

mactrack_resolver.php line 113
changed fom single quotes $sql_where = 'AND site_id=$site_id'; to double quotes $sql_where = "AND site_id=$site_id";

```

if ($site_id != '') {
	$sql_where = "AND site_id=$site_id";
}else{
	$sql_where = '';
}
```

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
