### ISSUE TITLE
No MacTrack Interfaces Found -  filter problem?

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_mactrack#57]
Hey guys,
does anyone else have this problem, too?
When I go to 'Devices' tab and click on the interface icon (View Interfaces) of a specific switch, mactrack shows all interfaces of ALL switches. But I just want to see the interfaces of the specific switch.
Furthermore, when I try to select the specific switch in the device filter, it says: "No MacTrack Interfaces Found". Only "All" works. But then I get the whole list again.

PS: I don't have this problem with "Show mac addresses". That works fine.

**Comment by jpobeda** [comment]
What version of MT are you using and please post an screenshot where we can also see the URL filter.

**Comment by jpobeda** [comment]
btw, also please try "clearing" the filter using the "clear" button, there is something odd with cacti's ui and some times the filters behave odd...or don't behave at all ehehe

**Comment by Axel577** [comment]
![mactrack](https://user-images.githubusercontent.com/28043745/35610329-2a617576-0661-11e8-8782-f478ec93c78a.JPG)

The relating url is: http://cacti/cacti/plugins/mactrack/mactrack_view_interfaces.php?report=interfaces&filter=&rows=-1&site_id=-1&device_id=3&issues=-2&bwusage=70&device_type_id=-1&totals=true

mactrack version 4.0

I tried the clear button, but that didn't help.

Oh, I noticed there is version 4.2, I should try that.

**Comment by jpobeda** [comment]
Can you try the latest version from develop branch? I remember to have
commited a fix for that last year. Will try to find it

**Comment by Axel577** [comment]
You are right, it works. Should have tried the new version before. Thanks.

May I ask you two unrelated questions?
Can you tell me what's the correct wildcard chracater for the system description?
And do you know how I can exclude interfaces from the list? For example Gi0/0. I tried that in the settings: (Vlan|Loopback|Null|Gi0/0|GigabitEthernet0/0)
but Gi0/0 still shows up.

**Comment by netniV** [comment]
The / is probably the problem.  Try making it \/ (that's a backslash then a forward-slash, not a letter V) to be formatted properly.

**Comment by Axel577** [comment]
![mactrack2](https://user-images.githubusercontent.com/28043745/35614678-35380258-0670-11e8-970a-41059fb670a4.JPG)

did it that way. But that doesn't work. But it says "whose mac results should be ignored" So maybe they actually mean the mac address list, and the interfaces itselves still show up.

**Comment by Axel577** [comment]
But I mean, that doesn't matter. I'm more curious about the wildcard character. Do you know that by any chance?
it says "The wildcard character is the 'mactrackign." That's not meaningful.

![mactrack3](https://user-images.githubusercontent.com/28043745/35614858-bdaa53b6-0670-11e8-8ba1-22aa4f210e3c.JPG)

**Comment by netniV** [comment]
No, I've seen that myself and wondered what the hell it was :)  I'll take a look.

**Comment by jpobeda** [comment]
We are all on the same boat, I didn't care either hahaha

@Axel577 

Let's say you've got a switch with this system desc

`System: Cisco IOS Software, **C2960X** Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E3, RELEASE SOFTWARE (fc3)Technical Support: http://www.cisco.com/techsupportCopyright (c) 1986-2015 by Cisco Systems, Inc.Compiled Wed 26-Aug-15 07:12 by prod_rel_team`

From all that shit you want to group your devices by for example C2960 because it's the platform and you know that's going to be different for C3850, C2950, and so and so.

You can see what's showing as sys descr if you go to Device Tracking > Devices and click on one of them.

You'll see **SNMP Information**

The ignore port I think are mainly for MAC Addresses.

**Comment by netniV** [comment]
So the problem is with the i18n functions taking the % sign and applying 'mactrack' to which is wrong because 'mactrack' is the module name.

**Comment by jpobeda** [comment]
I've just realized that it is on the wiki though

https://github.com/cacti/plugin_mactrack/wiki/Defining-Device-Types#device-types

> System Description Match Provide key information to help Device Tracking detect the type of device. The wildcard character is the % sign.

**Comment by Axel577** [comment]
okay thanks guys.
