### ISSUE TITLE
MAC Addresses have a trailing colon or dash, depending on delimeter selected.

### ISSUE THREAD

**Issue by crimsonllama** [Cacti/plugin_mactrack#64]
![image](https://user-images.githubusercontent.com/14912426/36216495-a050c85e-1174-11e8-8cfa-d26cb967a130.png)

We noticed sometime after upgrading to version 1.1.30(ish).

**Comment by netniV** [comment]
Which page are you seeing this on? I can give you some SQL to check the database values.

**Comment by crimsonllama** [comment]
/cacti/plugins/mactrack/mactrack_view_macs.php?report=macs

we see the colon within the DB as well.  We really appreciate the timely response!  this is a great product and are just a few steps away from making this thing awesome!

![image](https://user-images.githubusercontent.com/14912426/36223775-0be38046-118b-11e8-8eee-e3ff157b2491.png)

**Comment by crimsonllama** [comment]
To try and assist, we stood up another box, running version 1.1.28, and it was without the issue:

![image](https://user-images.githubusercontent.com/14912426/36225892-cb43f000-1191-11e8-87ee-5d2479e93454.png)

**Comment by netniV** [comment]
So this is using the same MACTRACK plugin but with two different outputs based solely on CACTI changing versions?

**Comment by netniV** [comment]
I believe that this isn't a CACTI issue but a MACTRACK issue, as I can see the code which generates this.

Try this patch and let me know if this corrects things for you:
```diff
diff --git a/lib/mactrack_functions.php b/lib/mactrack_functions.php
index 72fa09c..62d655f 100644
--- a/lib/mactrack_functions.php
+++ b/lib/mactrack_functions.php
@@ -1811,7 +1811,7 @@ function xform_mac_address($mac_address) {
                }else{ /* return is hex */
                        $mac = "";
                        for ($j = 0; $j < strlen($mac_address); $j++) {
-                               $mac .= bin2hex($mac_address[$j]) . read_config_option("mt_mac_delim");
+                               $mac .= bin2hex($mac_address[$j]) . ($j == (strlen($mac_address) - 1)? '' : read_config_option("mt_mac_delim"));
                        }
                        $mac_address = $mac;
                }
```

If so, I'll submit it as a full PR.

**Comment by netniV** [comment]
Updated the diff as it was the wrong one, sorry about that.

**Comment by crimsonllama** [comment]
Thank you so very, very much netniV!!!!  we have applied the change in the code on several boxes and have achieved the expected results!  

![image](https://user-images.githubusercontent.com/14912426/36263560-130dd7a4-1230-11e8-9507-10121726fa3c.png)

**Comment by jpobeda** [comment]
uhmmm and curious why this isn't happening on my installation. It may have got broken in recent commits.

**Comment by netniV** [comment]
Probably because your mac address is output in a full mac format so it keeps that.  Whereas if the output is only in binary format it converts it over.  As such, your probably never hitting the bin2hex code which has been in since the version first version of mactrack_functions.php:

```diff
+function xform_mac_address($mac_address) {
+       if (strlen($mac_address) == 0) {
+               $mac_address = "NOT USER";
+       }else{
+               if (strlen($mac_address) > 10) { /* return is in ascii */
+                       $mac_address = str_replace("HEX-00:", "", strtoupper($mac_address));
+                       $mac_address = str_replace("HEX-:", "", strtoupper($mac_address));
+                       $mac_address = str_replace("HEX-", "", strtoupper($mac_address));
+                       $mac_address = trim(str_replace("\"", "", $mac_address));
+                       $mac_address = str_replace(" ", read_config_option("mt_mac_delim"), $mac_address);
+                       $mac_address = str_replace(":", read_config_option("mt_mac_delim"), $mac_address);
+               }else{ /* return is hex */
+                       $mac = "";
+                       for ($j = 0; $j < strlen($mac_address); $j++) {
+                               $mac .= bin2hex($mac_address[$j]) . read_config_option("mt_mac_delim");
+                       }
+                       $mac_address = $mac;
+               }
+       }
+
+       return $mac_address;
+}
```

**Comment by jpobeda** [comment]
Thanks for the clarification! You're right

**Comment by netniV** [comment]
@crimsonllama Can we close this issue now?

**Comment by crimsonllama** [comment]
Most definitely. The patch has corrected he issue.  Thanks veey much!

**Comment by netniV** [comment]
Cool. Hit the close button then 👍
