### ISSUE TITLE
Proxy Option for downloading MAC/OUI Database

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#68]
Add proxy setting option for downloading the MAC/OUI Database from internet. 

Most of companies don't allow servers to go out to internet without proxy, so I think it's something reasonable to ask.

![image](https://user-images.githubusercontent.com/13456559/36751220-66b4d5fe-1c64-11e8-9830-f52a64c52640.png)

**Comment by netniV** [comment]
I would create them as separate requests since each would be it's own piece of work.  That way, if one person picks one to implement, someone else is free to work on the others.

**Comment by cigamit** [comment]
I think that this might be better served as a Cacti feature as I think there are other plugins that can benefit.  @jpobeda, if you could open a Cacti feature that would be great.  We can keep this one open and wait on that functionality here.

**Comment by TheWitness** [comment]
This is fixed now.  Please test.
