### ISSUE TITLE
Prompt confirmation not showing up

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#70]
Add a confirmation prompt for the following functions under Tracking Tools/Tracking Utilities

> Remove All Scan Results
> Remove All Aggregated Results
> Perform Aggregate Table Rebuild

![2018-02-28_08-53-09](https://user-images.githubusercontent.com/13456559/36751350-dcc1985e-1c64-11e8-8a03-db783e62b104.gif)

And probably Perform Database Maintenance and Refresh IEEE MAC/OUI Database need it as well.

I know there is a huge WARNING besides them but hey I think it's a good practice to always ask for confirmation.

**Comment by netniV** [comment]
This appears to have been implemented as a feature and uses the option name 'remove_verification'.  However, that option does not appear to be implemented in the MacTrack settings so it never appears.  Worse, there appears to be an update in Core 0_8_7c which renames remove_verification to deletion_verification:

```
grep "remove_verification" * -R
install/upgrades/0_8_7c.php:    db_install_execute("UPDATE settings SET name = 'deletion_verification' WHERE name = 'remove_verification'");
plugins/mactrack/mactrack_utilities.php:        if ((read_config_option('remove_verification') == 'on') && (!isset_request_var('confirm'))) {
plugins/mactrack/mactrack_utilities.php:        if ((read_config_option('remove_verification') == '') || (isset_request_var('confirm'))) {
plugins/mactrack/mactrack_utilities.php:        if ((read_config_option('remove_verification') == 'on') && (!isset_request_var('confirm'))) {
plugins/mactrack/mactrack_utilities.php:        if ((read_config_option('remove_verification') == '') || (isset_request_var('confirm'))) {
plugins/mactrack/mactrack_utilities.php:        if ((read_config_option('remove_verification') == 'on') && (!isset_request_var('confirm'))) {
plugins/mactrack/mactrack_utilities.php:        if ((read_config_option('remove_verification') == '') || (isset_request_var('confirm'))) {
```

So, it would appear that MacTrack is using an outdated option.  The 'Deletion Verification' setting comes under the general tab. I think I'm going to change remove_verification within mactrack to have it's own name mactrack_confirm with the option on the mactrack tab. The default of this will be the deletion_verification value.

**Comment by netniV** [comment]
This should now be resolved.

**Comment by jpobeda** [comment]
Changed the title to reflect that it was a bug rather than a feature request.

**Comment by netniV** [comment]
Have you had chance to test this?

**Comment by jpobeda** [comment]
I thought you did it, what's the rush on closing issues then? 

BTW, the confirmation now shows up

![image](https://user-images.githubusercontent.com/13456559/39609559-fb373c50-4f9d-11e8-9491-5cdf9b2c2880.png)

BUT

If you hit cancel or Delete, you get

![image](https://user-images.githubusercontent.com/13456559/39609563-084e3664-4f9e-11e8-95ef-7a0ba7a6bf89.png)

**Comment by jpobeda** [comment]
@netniV 

Just making sure you get an email. Fix doesn't work.

**Comment by netniV** [comment]
Sorry, thought I was just reenabling the functionality, didn't realise it was actually broken too 👍

**Comment by netniV** [comment]
At first I could not see the problem.  But then I realise that the base function is prefixing the $config['url_path'] so that is changing the URL location.  This should now be resolved.

**Comment by jpobeda** [comment]
Remove All Scan Results works fine now.

Remove All Aggregated Results doesn't
Perform Aggregate Table Rebuild doesn't

Same issue as previous.

**Comment by jpobeda** [comment]
@netniV Had a quick look, I think you also have to update lines 404 and 427.

Yep, that did the trick. I'll let you do those and feel free to close it now since I've tested it on mine.

Thanks btw =)

**Comment by netniV** [comment]
Weird, I thought I'd searched and replaced.  Maybe I didn't save that change.but I have now!
