### ISSUE TITLE
mactrack doesn't scan anymore.

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_mactrack#74]
Hey!
I don't know what happened, but mactrack doesn't perform scans anymore.
It says: Last scanned: 07-16 00:27:53
Next run time: 2018-07-16 00:37:53

![grafik](https://user-images.githubusercontent.com/28043745/39697342-e8e43148-51f0-11e8-9764-bd05938903c5.png)

What can I do?

(cacti 1.1.38 mactrack 4.3)

**Comment by netniV** [comment]
How did that last scan date become so out of whack?  What you can do is update mt_scan_date that is in the settings table to a value that would be appropriate for you.  One way to do that would be to take 86400 (seconds) * 61 (days) from the current value, eg:

```sql
update settings set value = value - (86400 * 61) where name = 'mt_scan_date';
```

**Comment by Axel577** [comment]
![grafik](https://user-images.githubusercontent.com/28043745/39699489-bd3ce270-51f9-11e8-972c-4f10fe48b499.png)

mmh, doesn't work for me..

**Comment by netniV** [comment]
You got the name part wrong, I had  written`mt_scan_date` in the `settings` table

**Comment by Axel577** [comment]
you are right!
But as you can see at the beginning of the screenshot, I exactly used your command, but it didn't change anything.
"Changed: 0"

**Comment by Axel577** [comment]
![grafik](https://user-images.githubusercontent.com/28043745/39702328-b7e7e6b6-5204-11e8-8c23-fdf011557b82.png)

**Comment by netniV** [comment]
No, your original screenshot had the wrong name, hence I was commenting on it 👍

**Comment by Axel577** [comment]
ups!

![grafik](https://user-images.githubusercontent.com/28043745/39741260-7d645412-5299-11e8-8bec-0b0cd56f5759.png)

**Comment by netniV** [comment]
In that case, just manually set the value using the format it currently has rather than using the calculated value.

**Comment by Axel577** [comment]
which value am I supposed to set?
A date in the past or in the future?

**Comment by netniV** [comment]
Try setting one for yesterday.

**Comment by Axel577** [comment]
It's stuck at every date:
![grafik](https://user-images.githubusercontent.com/28043745/39748706-0c50dbca-52b1-11e8-8598-f5b22497e7ef.png)

PS: mactrack installation was a new installation; I absolutely don't understand where it gets that weird date from

**Comment by cigamit** [comment]
Update to the latest version.  You can always force a run from the command line:

`php -q poller_mactrack.php --help`

For information on how to do that.  Reach out to @jdcoats if you want a tutorial.
