### ISSUE TITLE
Command Line does not show output

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#75]
I was trying to find out why I've got all the IP Addresses results using dhcp snooping function fucked up.
 
When I ran `php mactrack_scanner.php -d -id=7 ` I only get

> php -q mactrack_scanner.php -d -id=7
> 
> INFO: HOST: myswitch.domain.com, TYPE: Cisco IOS Software, C2960 Software (C296, TOTAL PORTS: 24                  , ACTIVE PORTS: 5

When/why all the debug stuff got removed? Any idea? 

I tried several devices, different platforms and scanning functions.

EDIT: Lucky me I did backup the previous version I was running on before testing @netniV fix for issue 70.

I've put that back and debugs are working again.

**Comment by netniV** [comment]
So issue 70 removes the debugs?

**Comment by jpobeda** [comment]
Not sure actually, it could have been even before that.
I normally update my plugins if I'm interested on some commits or fixes so, not sure.

How can we trace this back?

**Comment by jpobeda** [comment]
I'm actually thinking the problem might be on mactrack_functions.php

I'm pretty busy these days to start looking at the code, maybe next I can get to it and find out what/when got fucked up.

**Comment by jpobeda** [comment]
I've restored a copy from 10/01/2018 of mactrack_functions.php and the DEBUG outputs from cli are back. That explains before when rolled it back I thought were the latest changes but It's been a while since I run MT from cli for anything.

Now I've got to trace back what could have broken the ip dhcp snooping function.

I'll add further comments later on

**Comment by netniV** [comment]
It actually came in within #57 so I've made a minor change which should hopefully resolve the issue.

**Comment by jpobeda** [comment]
I'll try to test this before the end of this week.

**Comment by jpobeda** [comment]
I'm back..moving datacenters drains your life.

So @netniV , I've tested your patch and it works! output when running from cli works.

Now if you could help me to trace this other issue, I'd really appreciate it.

If you look at mactrack_cisco.php file on line 624 I left a 
`//mactrack_debug("SQL: " . $insert_string);` for troubleshooting. Now, look at this output. 

I'm thinking in 2 things,  xform_net_address or xform_mac_address. Any ideas?

> MACTRACK SQL: REPLACE INTO mac_track_ips
>                         (site_id,device_id,hostname,device_name,port_number,
>                         mac_address,ip_address,scan_date)
>                         VALUES (1,6,'myswitch.domain.com','myswitch','10112','','▒`▒ ','2018-05-15 09:23:30')
> 15/May/2018 09:30:48 - MACTRACK SQL: REPLACE INTO mac_track_ips
>                         (site_id,device_id,hostname,device_name,port_number,
>                         mac_address,ip_address,scan_date)
>                         VALUES (1,6,'myswitch.domain.com','myswitch','10107','','▒`▒','2018-05-15 09:23:30')
> 15/May/2018 09:30:48 - MACTRACK SQL: REPLACE INTO mac_track_ips
>                         (site_id,device_id,hostname,device_name,port_number,
>                         mac_address,ip_address,scan_date)
>                         VALUES (1,6,'myswitch.domain.com','myswitch','10101','','▒`▒-','2018-05-15 09:23:30')
> 15/May/2018 09:30:48 - MACTRACK SQL: REPLACE INTO mac_track_ips
>                         (site_id,device_id,hostname,device_name,port_number,
>                         mac_address,ip_address,scan_date)
>                         VALUES (1,6,'myswitch.domain.com','myswitch','10118','','▒`▒▒','2018-05-15 09:23:30')
> 15/May/2018 09:30:48 - MACTRACK SQL: REPLACE INTO mac_track_ips
>                         (site_id,device_id,hostname,device_name,port_number,
>                         mac_address,ip_address,scan_date)
>                         VALUES (1,6,'myswitch.domain.com','myswitch','10117','','▒`▒▒','2018-05-15 09:23:30')
> 15/May/2018 09:30:48 - MACTRACK SQL: REPLACE INTO mac_track_ips
>                         (site_id,device_id,hostname,device_name,port_number,
>                         mac_address,ip_address,scan_date)
>                         VALUES (1,6,'myswitch.domain.com','myswitch','10112','','▒`▒▒','2018-05-15 09:23:30')

**Comment by jpobeda** [comment]
Not sure how is that I'm getting those funny chars in there lol

BTW, if you want to strip the 2nd bug out of this issue and open a new one, let me know.

**Comment by netniV** [comment]
The characters are your IP address in binary form I think

**Comment by jpobeda** [comment]
IP and MAC BUT when did that change? How do we get this working again? Is there anything on dhcp snooping function we have to change?

**Comment by jpobeda** [comment]
Closing this one.
