### ISSUE TITLE
dlink switch vlan name is null

### ISSUE THREAD

**Issue by c8900219** [Cacti/plugin_mactrack#77]
I use dlink DGS-1500  switch 
Port Scanner use  get_dlink_l2_switch_ports
but snmp get  oid 1.3.6.1.2.1.17.7.1.4.3.1.1 (dot1qVlanStaticName)
D-link DGS-1500 response  "No data available in this sub-tree"
so insert vlan_anme is null because this Column not null

Error message on here 

18/06/02 01:10:14 - CMDPHP SQL Backtrace: (/plugins/mactrack/mactrack_scanner.php: 168 get_dlink_l2_switch_ports)(/plugins/mactrack/lib/mactrack_dlink.php: 60 get_dlink_l2_dot1dTpFdbEntry_ports)(/plugins/mactrack/lib/mactrack_dlink.php: 278 db_store_device_port_results)(/plugins/mactrack/lib/mactrack_functions.php: 2108 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
2018/06/02 01:10:14 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'vlan_name' cannot be null
2018/06/02 01:10:14 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO mac_track_temp_ports (site_id,device_id,hostname,device_name,vlan_id,vlan_name,mac_address,port_number,port_name,scan_date,authorized) VALUES ('8','17','140.131.*.***','F507','1',NULL,'60:a4:4c:**:**:**','24','','2018-06-02 01:10:08','0')'

**Comment by cigamit** [comment]
Can you update to the latest  version and let us know if this is still a problem.
