### ISSUE TITLE
MAC Duplication

### ISSUE THREAD

**Issue by avidpontoon** [Cacti/plugin_mactrack#78]
have setup MACTRACK on cacti network monitor as default and when testing, plugged a device (DEVICE-A) into fa0/1 on a cisco switch and the MAC address came up of the web interface. When I unplugged this device and moved it to fa0/2 the MAC address stayed on fa0/1 and was added to fa0/2 port on mactracker. Meaning that there are the same MAC address displayed on both fa0/1 and fa0/2 on the web interface. In an attempt to fix this, I plugged a new device (DEVICE-B) into fa0/1 and the MAC came up on the page. But mactracker didn't delete the previous MAC on that port and now I have two entries for the port fa0/1 with the MAC address for DEVICE-A on one and DEVICE-B on the other. How can I stop this duplication? I want only the newest last scanned MAC address to appear on the MAC address page.

Thanks in advance!

**Comment by jpobeda** [comment]
@avidpontoon 

Make sure you are filtering by "Most recent". Post an screenshot otherwise.

**Comment by TheWitness** [comment]
Correct.  MacTrack tracks the movement of the device if for example someones moving around a laptop.  So, this is not a bug.
