### ISSUE TITLE
Is this compatible with Windows OS?

### ISSUE THREAD

**Issue by andermat8** [Cacti/plugin_mactrack#79]
Running Cacti on Windows Server 2012 and I have installed mactrack and I can get mac addresses but no IP and hostname.  I can't appear to install arpwatch on a Windows server as there is no Windows install and there doesn't appear you can do this with cygwin64.  I can export the arpwatch database from another system.  Will this work or is the running of arpwatch a requirement?

**Comment by jpobeda** [comment]
@andermat8 as I understand arpwatch it's NOT a requirement if you're not going to use Mac Watch functionality.

Getting the IPs really depends on your topology. If by hostname you mean PTR records that comes from MacTrack settings.

Perform Reverse DNS Name Resolution, enable this option if you want mactrack to reverse resolv hostnames.

**Comment by andermat8** [comment]
Hi Javier, where in mactrack do I enable reverse DNS name resolution?  

Thanks!

**Comment by jpobeda** [comment]
Configuration/Settings/Device Tracking

![image](https://user-images.githubusercontent.com/13456559/42185981-f750572c-7e9e-11e8-9967-0e04cbb4928e.png)


Under DNS Settings..

![image](https://user-images.githubusercontent.com/13456559/42185962-e3d4d3b2-7e9e-11e8-8da6-4eae5a0d4138.png)

Close the case once you've tested it.

**Comment by andermat8** [comment]
This setting was already enabled.  When I look at the MAC to IP Report View columns ED IP Address and ED DNS Hostname are blank.  Do I require arpwatch in order to have these values populated?  Also, do you know of any good documentation on mactrack?

**Comment by jpobeda** [comment]
I've already answered that question..Do you know what is arpwatch for? Google it, will help you understand the tool.

MAC and IP Addresses come from pulling the devices using SNMP and the DNS hostnames come from the resolver.

Haven't seen anything better than [MacTrack Wiki](https://github.com/Cacti/plugin_mactrack/wiki) yet.

Post screenshot of the device type settings and also one those device settings that isn't showing IPs.

On the wiki, look at the troubleshooting section and run the commands from CLI and post the output.

**Comment by jpobeda** [comment]
To know the device id, go to edit one the devices and look at the url on your browser
https://cactiserver.com/cacti/plugins/mactrack/mactrack_devices.php?action=edit&device_id=6

**Comment by netniV** [comment]
ED DNS Hostname comes from `$port_result['dns_hostname']` which in turn is a result of `mactrack_view_get_ip_records()` which uses the following base SQL (without filtering):

```sql
SELECT mac_track_ips.*, mac_track_sites.site_name, mac_track_oui_database.*, mac_track_interfaces.ifName
FROM mac_track_ips
LEFT JOIN mac_track_sites ON 
    mac_track_ips.site_id = mac_track_sites.site_id
LEFT JOIN mac_track_oui_database ON
    mac_track_oui_database.vendor_mac=SUBSTRING(mac_track_ips.mac_address, 1, 8)
LEFT JOIN mac_track_interfaces ON 
    (mac_track_interfaces.device_id=mac_track_ips.device_id AND mac_track_interfaces.ifIndex=mac_track_ips.port_number
```

**Comment by netniV** [comment]
It does rely on arp_watch to be enabled to populate though:

```php
if (read_config_option('mt_arpwatch') == 'on') {
        $arp_db     = read_config_option('mt_arpwatch_path');
        $delim      = read_config_option('mt_mac_delim');
        $mac_ip_dns = array();

        if (file_exists($arp_db)) {
                $arp_dat = fopen($arp_db, 'r');

                if ($arp_dat) {
                        while (!feof($arp_dat)) {
                                $line = fgets($arp_dat, 4096);

                                if ($line != null) {
                                        $line = explode ('      ', $line);

                                        $mac_ad = explode(':',$line[0]);
                                        for ($k=0;$k<6;$k++) {
                                                $mac_ad[$k] = strtoupper($mac_ad[$k]);
                                                if (1 == strlen($mac_ad[$k])) {
                                                        $mac_ad[$k] = '0' . $mac_ad[$k];
                                                }
                                        }

                                        /* create the mac address */
                                        $mac = $mac_ad[0] . $delim . $mac_ad[1] . $delim . $mac_ad[2] 

                                        /* update the array */
                                        $mac_ip_dns[$mac]['ip']  = $line[1];
                                         /* update the array */
                                         $mac_ip_dns[$mac]['ip']  = $line[1];
                                         $mac_ip_dns[$mac]['dns'] = $line[3];
                                 }
                         }
                         fclose($arp_dat);

                         mactrack_debug('ARPWATCH: IP, DNS & MAC collection complete with ArpWatch');
                 } else {
                         cacti_log("ERROR: cannot open file ArpWatch database '$arp_db'");exit;
                 }
         }
 }
```

**Comment by andermat8** [comment]
Okay, so if I'm running Cacti on a Windows server then mactrack will not fully work because arpwatch can't run on Windows.  At least I can't figure out a way to make it work.

**Comment by netniV** [comment]
I had the thought to tweak this to use `arp -a` instead which gives outputs in the form of:

```
  Internet Address      Physical Address     Type
  <ip address>          <mac address>        dynamic
  <ip address>          <mac address>        dynamic
  <ip address>          <mac address>        dynamic
  <ip address>          <mac address>        static
  <ip address>          <mac address>        dynamic
```

But that would not give the DNS, so for each line you would have to run a `nslookup <ip>` and then try to match the output such as:

```
> nslookup 10.17.2.11
Server:  dnsname.example.local
Address:  10.17.2.11

Name:    dnsname.example.local
Address:  10.17.2.11
```

For each address, that may take a long time.  The other alternative is to use the built in name resolution functions if PHP has them.

**Comment by cigamit** [comment]
The original author was monitoring almost 4000 switches, routers, and hubs on a 2 socket server running Windows2003 and 8GB of memory.  So, yes, it works.  I would suggest it runs much better on Linux.
