### ISSUE TITLE
MACTRACK ERROR: cannot start MAC Tracking process.

### ISSUE THREAD

**Issue by nhenpanha** [Cacti/plugin_mactrack#80]
Hi team,

could you help to check the below alert?
![image](https://user-images.githubusercontent.com/11862935/41961083-acf5c252-7a1b-11e8-8933-36d18e234900.png)

**Comment by netniV** [comment]
There is a process table in the MySQL database that lists processes that have been started.  If it sees that a process with that ID still exists, it will assume it's currently in progress already and prevent it from running again.

**Comment by nhenpanha** [comment]
Is it normal?

**Comment by netniV** [comment]
It can happen.  If it's happening and nothing else is processing, that would suggest an error.

**Comment by nhenpanha** [comment]
I see, thanks for your information. I got it now...

**Comment by jpobeda** [comment]
In addition, pay attention to how long it normally takes to run, it might indicate possible issues introduced by latency on remote switches.

**Comment by netniV** [comment]
Closing now, if there's still an issue let us know.
