### ISSUE TITLE
Add support for FontAwesome 5.0 under Cacti 1.2

### ISSUE THREAD

**Issue by fcafultzj** [Cacti/plugin_mactrack#81]
the console nav icon doesn't show up, after some research, turns out fa-shield is only available in the pro release.

_**UPDATE: thought I should mention this only effects the current cacti-develop code for 1.2.0. Since it has the updated themes**_

[fa-shield](https://fontawesome.com/icons/shield?style=solid)
[fa-shield-alt](https://fontawesome.com/icons/shield-alt?style=solid)

So to get this to be fixed change in setup.php (line 1381):
From:
`$menu_glyphs[__('Device Tracking', 'mactrack')] = 'fa fa-shield';`

To:
`$menu_glyphs[__('Device Tracking', 'mactrack')] = 'fa fa-shield-alt';`

[setup.php#L1381](https://github.com/Cacti/plugin_mactrack/blob/a36d9aad3706d1149f1f3f96a09b81ee7aad1257/setup.php#L1381)

**Not really a substantial "issue" to warrant a pull request but it's a visual annoyance that I seeked to resolve 😃**

**Comment by netniV** [comment]
Good spot, I've added a 1.2 check since that is when the shield icon changed for us under FA 5.0.  If it detects an older Cacti version it should still use the older version instead.
