### ISSUE TITLE
device type shows twice / % does not work with Vendor SNMP Object ID Match

### ISSUE THREAD

**Issue by gllewellyn** [Cacti/plugin_mactrack#82]
If I edit a device type a device type it shows twice. If I delete one it deletes both. Also % does not seem to work with 
![device type](https://user-images.githubusercontent.com/37145853/42874432-af5f9440-8a70-11e8-8124-001d42d0b90b.jpg)

Cacti Version 1.1.37 
Mactrack 4.2

**Comment by netniV** [comment]
Once you have edited a device type, can you run the following SQL for me to see if they do appear in the database more than once?

```sql
select * from mac_track_device_types
```

**Comment by gllewellyn** [comment]
```sql
MariaDB [cacti]> select * from mac_track_device_types;
```
| device_type_id | description | vendor | device_type | sysDescr_match | sysObjectID_match            | scanning_function              | ip_scanning_function   | dot1x_scanning_function | serial_number_oid | lowPort | highPort |
| --------------:| ----------- | ------ | -----------:| -------------- | ---------------------------- | ------------------------------ | ---------------------- | ----------------------- | ----------------- | -------:| --------:|
|              7 | HP 5900     |        | 1           |                | .1.3.6.1.4.1.25506.11.1.120  | get_generic_dot1q_switch_ports | get_standard_arp_table | get_cisco_dot1x_table   |                   |       0 |        0 |
|              3 | HP 5930     |        | 1           |                | .1.3.6.1.4.1.25506.11.1.144  | get_generic_dot1q_switch_ports | get_standard_arp_table | 0                       |                   |       0 |        0 |
|             20 | Cisco 2960  |        | 1           |                | .1.3.6.1.4.1.9.1.1208        | get_IOS_dot1dTpFdbEntry_ports  | get_standard_arp_table | 0                       |                   |       0 |        0 |
|             19 | Nexus       |        | 1           |                | .1.3.6.1.4.1.9.12.3.1.3.     | get_IOS_dot1dTpFdbEntry_ports  | get_standard_arp_table | 0                       |                   |       0 |        0 |
|             19 | Nexus       |        | 1           |                | .1.3.6.1.4.1.9.12.3.1.3.%%%% | get_IOS_dot1dTpFdbEntry_ports  | get_standard_arp_table | 0                       |                   |       0 |        0 |

5 rows in set (0.00 sec)

**Comment by netniV** [comment]
I reformatted your post for easier reading (hope you don't mind).

I presume you simply added the % sign to the end of the sysObjectID field which then caused the above to occur?

**Comment by gllewellyn** [comment]
yes. but also happen if you add any change.

**Comment by jpobeda** [comment]
I remember that issue, was fixed last year at the very least.. Even changing the scanning function was creating duplicated entries with the same device_type_id.

https://github.com/Cacti/plugin_mactrack/issues/10

**Comment by gllewellyn** [comment]
I thought fix 10 was included in 4.2 or am I just miss understanding.

**Comment by netniV** [comment]
Fix 10 was patched and included in the 4.0 release.

**Comment by jpobeda** [comment]
Uhm..I just tested applying the % to SysDescription match and it gets duplicated..corner case?

**Comment by netniV** [comment]
Sounds like it.  Think you can patch it?

**Comment by jpobeda** [comment]
Every time I code something millions of galaxies die and thousands of developers cry

**Comment by netniV** [comment]
Not this one ;-)

**Comment by jpobeda** [comment]
@netniV , I don't see anything wrong in the code but I did try running the query manually and it duplicates it, not sure what violations could cause a dup..

look:

`INSERT INTO mac_track_device_types (`device_type_id`, `description`, `vendor`, `device_type`, `sysDescr_match`, `sysObjectID_match`, `serial_number_oid`, `scanning_function`, `ip_scanning_function`, `dot1x_scanning_function`, `lowPort`, `highPort`) VALUES (7, 'CAT 2960', 'Cisco', '1', 'C29602', '', '', '0', '0', '0', 0, 0) ON DUPLICATE KEY UPDATE `description`=VALUES(`description`), `vendor`=VALUES(`vendor`), `device_type`=VALUES(`device_type`), `sysDescr_match`=VALUES(`sysDescr_match`), `sysObjectID_match`=VALUES(`sysObjectID_match`), `serial_number_oid`=VALUES(`serial_number_oid`), `scanning_function`=VALUES(`scanning_function`), `ip_scanning_function`=VALUES(`ip_scanning_function`), `dot1x_scanning_function`=VALUES(`dot1x_scanning_function`), `lowPort`=VALUES(`lowPort`), `highPort`=VALUES(`highPort`);`

```
| mac_track_device_types | CREATE TABLE `mac_track_device_types` (
  `device_type_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `description` varchar(100) NOT NULL DEFAULT '',
  `vendor` varchar(40) NOT NULL DEFAULT '',
  `device_type` varchar(10) NOT NULL DEFAULT '0',
  `sysDescr_match` varchar(20) NOT NULL DEFAULT '',
  `sysObjectID_match` varchar(40) NOT NULL DEFAULT '',
  `scanning_function` varchar(100) NOT NULL DEFAULT '',
  `ip_scanning_function` varchar(100) NOT NULL,
  `dot1x_scanning_function` varchar(100) NOT NULL,
  `serial_number_oid` varchar(100) DEFAULT '',
  `lowPort` int(10) unsigned NOT NULL DEFAULT '0',
  `highPort` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`sysDescr_match`,`sysObjectID_match`,`device_type`),
  KEY `device_type` (`device_type`),
  KEY `device_type_id` (`device_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
```

**Comment by jpobeda** [comment]
Shouldn't device_type_id be a unique key?

**Comment by netniV** [comment]
If we already have an id, then we should not be inserting but updating. Simple logic.  I will investigate this later today and see if I can see a way to improve it (unless you'd like to make some crying and dying scenario's? 🙈 )

**Comment by jpobeda** [comment]
It calls cacti's sql_save function which "on duplicate updates" but something on the table structure violates the mysql statement I think..You better take care of this =D <3

**Comment by gllewellyn** [comment]
any update

**Comment by netniV** [comment]
I haven't had time to investigate this further.  I may be able to look at this when I look at the other issue, but this one is likely to need more care to be taken as changing a primary key can be disastrous.

**Comment by xmacan** [comment]
Sometimes  happens  on Device tracking -> Devices too. 
I have device without site, edit - only add site and after save I have two devices - with and without sites. 
MariaDB [cacti]> select site_id,device_id,host_id from  mac_track_devices;
+---------+-----------+---------+
| site_id | device_id | host_id |
+---------+-----------+---------+
|       0 |         4 |     197 |
|       1 |         4 |     197 |

**Comment by xmacan** [comment]
And with "double devices" tracking process failed:
2019/06/09 15:13:07 - MACTRACK ERROR: Site not found in database. Can not continue.
2019/06/09 15:13:07 - MACTRACK ERROR: Site not found in database. Can not continue.

**Comment by netniV** [comment]
Can you remind me what the url is when you are doing this?

**Comment by xmacan** [comment]
I agree with @jpobeda - device_type_id must be key or unique ..
From https://mariadb.com/kb/en/library/insert-on-duplicate-key-update/ :
INSERT ... ON DUPLICATE KEY UPDATE is a MariaDB/MySQL extension to the INSERT statement that, if it finds a **duplicate unique or primary key**, will instead perform an UPDATE.

But device_type_id isn't unique:
MariaDB [cacti]> describe mac_track_device_types;
+-------------------------+------------------+------+-----+---------+----------------+
| Field                         | Type                   | Null | Key    | Default | Extra          |
+-------------------------+------------------+------+-----+---------+----------------+
| device_type_id          | int(10) unsigned | NO   | **MUL** | NULL    | auto_increment |

Works fine after 
 **alter table mac_track_device_types modify device_type_id int(10) unique auto_increment;**

**Comment by xmacan** [comment]
> 
> 
> Can you remind me what the url is when you are doing this?

....plugins/mactrack/mactrack_view_sites.php?report=sites
And icon Rescan site

**Comment by vKnmnn** [comment]
I think this is not fixed yet. I'm having the same issue here.
