### ISSUE TITLE
Un-know web page return when doing certain tasks

### ISSUE THREAD

**Issue by gllewellyn** [Cacti/plugin_mactrack#83]
When I try an do certain task I get a black web page.

Any one got any advise.

![1](https://user-images.githubusercontent.com/37145853/43131951-d615c088-8f29-11e8-854d-ccc2efc74500.jpg)
![2](https://user-images.githubusercontent.com/37145853/43131955-d9fe5ad4-8f29-11e8-9f1c-d62068888440.jpg)
![3](https://user-images.githubusercontent.com/37145853/43131958-dbbbf458-8f29-11e8-8ce7-39f8b1691bd0.jpg)

**Comment by netniV** [comment]
What version of cacti are you using?

**Comment by gllewellyn** [comment]
4.2

**Comment by netniV** [comment]
That's mactrack, not cacti 👍

**Comment by gllewellyn** [comment]
Sorry....  need to read things :)
Cacti Version 1.1.37

**Comment by netniV** [comment]
Are there any errors in the log files?  We've made some changes to the way dynamic callbacks are working in later versions but I'm not sure if that's 1.1.38 or 1.2  so for now I'm going to work on the assumption that the problem is an error being flagged and it not reporting it properly.

**Comment by gllewellyn** [comment]
Nothing in the error logs I can see relate to it.

**Comment by netniV** [comment]
How about in the apache error logs?

**Comment by gllewellyn** [comment]
[root@gcp3451prdsrv01 httpd]# more error_log
........
[Tue Jul 24 11:42:12.635256 2018] [mpm_prefork:notice] [pid 861] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Jul 24 11:42:43.909781 2018] [core:notice] [pid 861] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Tue Jul 24 11:42:43.922336 2018] [suexec:notice] [pid 861] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Jul 24 11:42:43.961599 2018] [auth_digest:notice] [pid 861] AH01757: generating secret for digest authentication ...
[Tue Jul 24 11:42:43.962881 2018] [lbmethod_heartbeat:notice] [pid 861] AH02282: No slotmem from mod_heartmonitor
[Tue Jul 24 11:42:44.566046 2018] [mpm_prefork:notice] [pid 861] AH00163: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/5.6.37 configured -- resuming normal operations
[Tue Jul 24 11:42:44.566101 2018] [core:notice] [pid 861] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

[root@gcp3451prdsrv01 httpd] more ssl_error_log


[Tue Jul 24 11:42:43.925017 2018] [ssl:warn] [pid 861] AH01909: RSA certificate configured for gcp3451prdsrv01.c.slb-it-business-systems-prod.internal:443 does NOT include an ID which matches the server name
[Tue Jul 24 11:42:43.963747 2018] [ssl:warn] [pid 861] AH01909: RSA certificate configured for gcp3451prdsrv01.c.slb-it-business-systems-prod.internal:443 does NOT include an ID which matches the server name
[Tue Jul 24 12:42:23.908898 2018] [:error] [pid 1198] [client 136.250.243.57:52433] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:42:23.909046 2018] [:error] [pid 1198] [client 136.250.243.57:52433] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:42:23.909137 2018] [:error] [pid 1198] [client 136.250.243.57:52433] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:42:23.909215 2018] [:error] [pid 1198] [client 136.250.243.57:52433] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:44:50.118257 2018] [:error] [pid 1196] [client 136.250.243.57:52504] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:44:50.118386 2018] [:error] [pid 1196] [client 136.250.243.57:52504] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:44:50.118469 2018] [:error] [pid 1196] [client 136.250.243.57:52504] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:44:50.118548 2018] [:error] [pid 1196] [client 136.250.243.57:52504] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[root@gcp3451prdsrv01 httpd]#




[root@gcp3451prdsrv01 httpd]# date
Tue Jul 24 12:45:16 UTC 2018
[root@gcp3451prdsrv01 httpd]#

**Comment by netniV** [comment]
Are you running PHP 7.2 per chance?

**Comment by gllewellyn** [comment]
Here is info of what is running :-

Date Wed, 25 Jul 2018 09:08:13 +0000 
Cacti Version 1.1.37 
Cacti OS unix 
RSA Fingerprint 80:6a:64:f4:30:b0:ec:ba:1e:62:09:83:00:a2:a6:67 
NET-SNMP Version NET-SNMP version: 5.7.2  
RRDtool Version RRDtool 1.4.x  
Devices 150 
Graphs 24,451 
Data Sources Script/Command: 5
SNMP Query: 24,444
Script Query: 2
Total: 24,451 

Poller Information 

Interval 300 
Type SPINE 1.1.38 Copyright 2004-2017 by The Cacti Group 
Items Action[0]: 73,332
Action[1]: 9
Total: 73,341 
Concurrent Processes 1 
Max Threads 8 
PHP Servers 4 
Script Timeout 25 
Max OID 10 
Last Run Statistics Time:99.6180 Method:spine Processes:1 Threads:8 Hosts:150 HostsPerProcess:150 DataSources:73341 RRDsProcessed:24451 

System Memory 

MemTotal 16,267.06 MB 
MemFree 9,754.14 MB 
Buffers 2.08 MB 
Cached 4,664.3 MB 
Active 4,759.77 MB 
Inactive 1,166.34 MB 
SwapTotal 0 MB 
SwapFree 0 MB 

PHP Information 

PHP Version 5.6.37 
PHP OS Linux 
PHP uname Linux gcp3451prdsrv01 3.10.0-862.9.1.el7.x86_64 #1 SMP Wed Jun 27 04:30:39 EDT 2018 x86_64 
PHP SNMP Installed 
max_execution_time 30 
memory_limit 1024M

**Comment by netniV** [comment]
I've added a change that should resolve this in the latest development version.

**Comment by gllewellyn** [comment]
Tested with the changes to mactrack_devices.php and still same problem.

Do not get errors in ssl_error_log now.

more ssl_error_log

....
[Tue Jul 24 12:44:50.118469 2018] [:error] [pid 1196] [client 136.250.243.57:52504] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Tue Jul 24 12:44:50.118548 2018] [:error] [pid 1196] [client 136.250.243.57:52504] PHP Warning:  Variable passed to each() is not an array or object in /usr/share/cacti/plugins/mactrack/mactrack_devices.php on line 159, referer: https:/
/10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
[Wed Jul 25 09:33:28.953344 2018] [autoindex:error] [pid 1581] [client 163.185.65.7:42139] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forb
idden by Options directive
[Wed Jul 25 09:55:13.079452 2018] [ssl:warn] [pid 13203] AH01909: RSA certificate configured for gcp3451prdsrv01.c.slb-it-business-systems-prod.internal:443 does NOT include an ID which matches the server name
[Wed Jul 25 09:55:13.106344 2018] [ssl:warn] [pid 13203] AH01909: RSA certificate configured for gcp3451prdsrv01.c.slb-it-business-systems-prod.internal:443 does NOT include an ID which matches the server name
[Wed Jul 25 09:56:22.357367 2018] [ssl:warn] [pid 862] AH01909: RSA certificate configured for gcp3451prdsrv01.c.slb-it-business-systems-prod.internal:443 does NOT include an ID which matches the server name
[Wed Jul 25 09:56:22.389264 2018] [ssl:warn] [pid 862] AH01909: RSA certificate configured for gcp3451prdsrv01.c.slb-it-business-systems-prod.internal:443 does NOT include an ID which matches the server name
[root@gcp3451prdsrv01 httpd]#

**Comment by netniV** [comment]
OK, so solved the logged errors, but now you have one that isn't being logged.  It may be badly formatted HTML... going to be tricky to debug that as I don't have any devices in mactrack on my dev box.  Could you possibly check in the dev tools of your browser? If you are using Chrome, you can find the document request and then tap the preview button to show what it looks like.

1. use chrome and navigate to the page that shows the selected list with the continue button
1. open dev tools (on my system that is as simple as pressing f12)
1. click the network tab
1. click continue on the web page
1. look for the "Document" that was requested 
    ![image](https://user-images.githubusercontent.com/9052188/43197159-2f3ecde8-9002-11e8-9094-83330e24d46c.png)
1. click the name on the left column, then preview
   ![image](https://user-images.githubusercontent.com/9052188/43197184-48152d94-9002-11e8-8301-268c93526157.png)

I am curious if it displays properly there or not.  Also, if you click the Response tab, can you copy the contents of that and paste between a header/footer of three backticks ` so that GitHub shows the code properly.

**Comment by gllewellyn** [comment]
![21](https://user-images.githubusercontent.com/37145853/43198122-0f07949c-8ffd-11e8-8b53-83fa14df953e.jpg)

![22](https://user-images.githubusercontent.com/37145853/43198141-227e8670-8ffd-11e8-9579-796afba58574.jpg)

**Comment by netniV** [comment]
OK, if you could do that again, it's actually not a Document but an xhr and is the second mac_track_devices.php entry which on your screen has a status of 200.  The first with a status 302 is were it's doing the original work.

If you could get the response and preview info that would be good.

**Comment by gllewellyn** [comment]
![31](https://user-images.githubusercontent.com/37145853/43207857-86603fa6-9018-11e8-92dd-ac4feaf0495e.jpg)
![32](https://user-images.githubusercontent.com/37145853/43207865-89ae84d8-9018-11e8-9c51-ee6176f5aea0.jpg)
![33](https://user-images.githubusercontent.com/37145853/43207869-8c73d2ea-9018-11e8-9a37-a4d014696f79.png)
![xx](https://user-images.githubusercontent.com/37145853/43207883-954568ac-9018-11e8-9b6f-e8e357e5fec2.jpg)

![34](https://user-images.githubusercontent.com/37145853/43207881-922fbef6-9018-11e8-88de-a968a204ac17.jpg)

**Comment by netniV** [comment]
That second to last picture is the first bit I wanted, if you clicked the response tab next to it, was it empty or did it contain something?  IF it contains anything, can you paste it here.

**Comment by gllewellyn** [comment]
![41](https://user-images.githubusercontent.com/37145853/43249026-1d06ee10-90a9-11e8-963d-0a7ab9f813d3.jpg)
![42](https://user-images.githubusercontent.com/37145853/43249028-1ed00bd2-90a9-11e8-917c-1b7f20708e9c.jpg)
![43](https://user-images.githubusercontent.com/37145853/43249031-209bcb9a-90a9-11e8-9bba-5ffdb0bc7509.jpg)

**Comment by netniV** [comment]
OK, so I wasn't expecting no response at all.  Can you let me know what the Headers say?

**Comment by gllewellyn** [comment]
Request URL: https://10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php?header=false
Request Method: POST
Status Code: 302 Found
Remote Address: 10.196.163.218:443
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: Keep-Alive
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Thu, 26 Jul 2018 09:12:58 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=99
Last-Modified: Thu, 26 Jul 2018 09:12:58 GMT
Location: mactrack_devices.php
P3P: CP="CAO PSA OUR"
Pragma: no-cache
Server: Apache
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/5.6.37
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 156
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: Cacti=u8at0j91dk5gon0kmp50df85f6
Host: 10.196.163.218
Origin: https://10.196.163.218
Referer: https://10.196.163.218/cacti/plugins/mactrack/mactrack_devices.php
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
X-Requested-With: XMLHttpRequest
header: false
action: actions
selected_items: a:1:{i:0;s:1:"4";}
drp_action: 5
__csrf_magic: sid:34c03af87adf1e1ed1c3eff2e7cedecde9ad3385,1532596363

**Comment by netniV** [comment]
There were no response headers?

**Comment by netniV** [comment]
Never mind, I think I see the problem, this feature hasn't been properly implemented.  I need to double check what it should be setting as I only see one port field, not an upper/lower at the moment.  There will be a patch coming.

**Comment by netniV** [comment]
Can you clarify for me what you expect that option to change?  Or is it a case you were trying to see what it did?  I'm expecting it to change the __Ports to ignore__ option:

![image](https://user-images.githubusercontent.com/9052188/43258269-27ab1d16-90ca-11e8-8771-4296460fc848.png)

**Comment by gllewellyn** [comment]
I was  go to select a few devices and try and see what port device values I can bulk change. In this case i want to change the site 20 device were in.

**Comment by gllewellyn** [comment]
So expecting the page that allows port device values to come up. Which it does not.

**Comment by netniV** [comment]
The description of the option is to change upper/lower port values.  This would suggest the connection ports being used, not individual values such as the description, etc.  Personally, I think it's a useless option because from what I can see there is no upper/lower port settings (not sure if there were in the past).  

As such, I am going to change it to allow you to modify the "Ports to Ignore" value since that is the closest match I can find.  I am half tempted to just remove that dropdown option all together (less work!)

**Comment by gllewellyn** [comment]
any update

**Comment by netniV** [comment]
Sorry, been busy with 1.2 work which had some major updates.  I'll get to this over the next day or two.

**Comment by netniV** [comment]
OK, I believe that this should now be resolved.  I also tightened up security a bit by ensuring that the field names on the URL's do actually match the expected field names of the action being taken.
