### ISSUE TITLE
CMDPHP ERROR: A DB Exec Failed!, Error: Column 'device_type' cannot be null

### ISSUE THREAD

**Issue by Arkansmith** [Cacti/plugin_mactrack#86]
Cacti version: 1.1.37
Mactrack version: 4.2
 
I added some devices: two Cisco Catalyst 3560 and one Cisco 2960.  I have not manually added the device types.  I clicked on the Rescan button in hopes of it automatically adding the Device Types (not sure if it works that way or not).  The log shows three versions of this error (with description differences):

```
08/08/2018 17:37:47 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'device_type' cannot be null
08/08/2018 17:37:47 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO mac_track_device_types (description, vendor, device_type, sysDescr_match, sysObjectID_match) VALUES ('C2960X-UNIVERSALK9-M (2)','Cisco',NULL,'C2960X-UNIVERSALK9-M','.1.3.6.1.4.1.9.1.1208')'
08/08/2018 17:37:47 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_device_types.php: 99 mactrack_rescan_device_types)(/plugins/mactrack/mactrack_device_types.php: 461 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
08/08/2018 17:37:47 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined index: device_type in file: /usr/share/cacti/plugins/mactrack/mactrack_device_types.php on line: 461

```
I'm no programmer, but looking through the code in mactrack_device_types.php, I can't see where $item['device_type'] is ever assigned a value, which is why it is trying to populate the database with a Null (and failing), but I might be just overlooking.

device_type is part of the Primary Key in the DB, so I see why it can't be null.  Should the code default to an acceptable device_type instead of null?

Sorry if this "problem" is just user error.

Thanks,
Kevin

**Comment by netniV** [comment]
If you check out mactrack_setup_table_new() in setup.php you will find the table definitions. See if your tables match them and if not, that’s probably why your getting the error.

**Comment by jpobeda** [comment]
@Arkansmith 

Read the [wiki](https://github.com/Cacti/plugin_mactrack/wiki), Mandatory steps are: you need a site and you need a device types. You're trying to get it going the other way around.

You declare device types, specifying the scanning functions and when mactrack runs, allocates devices matching criteria to device types and then execute the scanning functions.
