### ISSUE TITLE
mactrack 4.2 trailing colon on end of mac addresses.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#88]
mactrack 4.2 trailing colon on end of mac addresses.
![screen shot 08-20-18 at 04 34 pm](https://user-images.githubusercontent.com/42470924/44365249-c15f8300-a4b8-11e8-96c7-f1f10061af27.PNG)

**Comment by netniV** [comment]
I think this was fixed with the latest development version.

https://github.com/Cacti/plugin_mactrack/issues/64

Yup it was, so I'm going to go ahead and close this for now.  If you are still having the issue, I will have to review it again.

**Comment by jdcoats** [comment]
I just downloaded the development .zip and the problem remains. It is 4.2

**Comment by netniV** [comment]
So I've pushed through an update to this and tested it using:

```php
<?php
include('mactrack_functions.php');
$macs = array('fa-cc-01-de-a1-b2 ' => 'string', ' af-c1-ee-01-02-03- ' => 'string', hex2bin('b2a1de01ccfa') => 'bin');

$seps = array('x','-',':');
global $config_sep;
foreach ($seps as $sep) {
        echo "With '$sep' separator\n";
        $config_sep = $sep;
        foreach ($macs as $mac => $type) {
                $src = ($type == 'bin' ? bin2hex($mac) : $mac);
                printf("%6s %20s = %-20s\n", $type, $src, xform_mac_address($mac));
        }
        echo "\n";
}

function read_config_option($var) {
        global $config_sep;
        return $config_sep;
}

function __($value) {
        return $value;
}
```

which resulted in:

```console
With 'x' separator
string   fa-cc-01-de-a1-b2  = FAxCCx01xDExA1xB2   
string  af-c1-ee-01-02-03-  = AFxC1xEEx01x02x03   
   bin         b2a1de01ccfa = B2xA1xDEx01xCCxFA   

With '-' separator
string   fa-cc-01-de-a1-b2  = FA-CC-01-DE-A1-B2   
string  af-c1-ee-01-02-03-  = AF-C1-EE-01-02-03   
   bin         b2a1de01ccfa = B2-A1-DE-01-CC-FA   

With ':' separator
string   fa-cc-01-de-a1-b2  = FA:CC:01:DE:A1:B2   
string  af-c1-ee-01-02-03-  = AF:C1:EE:01:02:03   
   bin         b2a1de01ccfa = B2:A1:DE:01:CC:FA   
```

So, I think i've covered most situations now.

**Comment by jdcoats** [comment]
problem still exists.

**Comment by netniV** [comment]
Without seeing your data as it's being queried, and tracking it through, I can't see how you'd still be having this issue given the above test on the mac address translation.

It almost sounds like something is not using the `xform_mac_address()` function to get the mac address.

**Comment by jdcoats** [comment]
I spoke too soon. The new data moving forward is fixed. Just the previous data is not fixed.

**Comment by netniV** [comment]
Once it refreshes it, it will sort itself out.  You could right an SQL query to strip it off

**Comment by jdcoats** [comment]
Thanks! working on it
