### ISSUE TITLE
cant create new device types

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#90]
2018/08/21 12:01:26 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined index: dot1x_scanning_function in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_device_types.php on line: 958  
2018/08/21 12:01:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_device_types.php: 109 mactrack_device_type)(/plugins/mactrack/mactrack_device_types.php: 958 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/08/21 12:01:26 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined index: dot1x_scanning_function in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_device_types.php on line: 958  
2018/08/21 12:01:26 - DBCALL ERROR: SQL Save Failed for Table 'mac_track_device_types'. SQL:'INSERT INTO mac_track_device_types (`device_type_id`, `description`, `vendor`, `device_type`, `sysDescr_match`, `sysObjectID_match`, `scanning_function`, `ip_scanning_function`, `dot1x_scanning_function`, `lowPort`, `highPort`) VALUES (0, 'Nexus 7K(1)', 'Cisco', '2', '--dup--n7000', '--dup--', 'get_IOS_dot1dTpFdbEntry_ports', 'get_standard_arp_table', NULL, 0, 0) ON DUPLICATE KEY UPDATE `description`=VALUES(`description`), `vendor`=VALUES(`vendor`), `device_type`=VALUES(`device_type`), `sysDescr_match`=VALUES(`sysDescr_match`), `sysObjectID_match`=VALUES(`sysObjectID_match`), `scanning_function`=VALUES(`scanning_function`), `ip_scanning_function`=VALUES(`ip_scanning_function`), `dot1x_scanning_function`=VALUES(`dot1x_scanning_function`), `lowPort`=VALUES(`lowPort`), `highPort`=VALUES(`highPort`)'

**Comment by jdcoats** [comment]
**Every time I click on Device Tracking/Device Types menu option I get about 50 of these errors:**
`2018/08/21 12:09:30 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_device_types.php: 109 mactrack_device_type)(/plugins/mactrack/mactrack_device_types.php: 958 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/08/21 12:09:30 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined index: dot1x_scanning_function in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_device_types.php on line: 958  
`
**When I try to create a new device type I get:**
 `2018/08/21 12:00:39 - DBCALL ERROR: SQL Save Failed for Table 'mac_track_device_types'. SQL:'INSERT INTO mac_track_device_types (`device_type_id`, `description`, `vendor`, `device_type`, `sysDescr_match`, `sysObjectID_match`, `serial_number_oid`, `scanning_function`, `ip_scanning_function`, `dot1x_scanning_function`, `lowPort`, `highPort`) VALUES (0, 'Nexus 5000', 'Cisco', '1', '', '', '', '0', '0', '0', 0, 0) ON DUPLICATE KEY UPDATE `description`=VALUES(`description`), `vendor`=VALUES(`vendor`), `device_type`=VALUES(`device_type`), `sysDescr_match`=VALUES(`sysDescr_match`), `sysObjectID_match`=VALUES(`sysObjectID_match`), `serial_number_oid`=VALUES(`serial_number_oid`), `scanning_function`=VALUES(`scanning_function`), `ip_scanning_function`=VALUES(`ip_scanning_function`), `dot1x_scanning_function`=VALUES(`dot1x_scanning_function`), `lowPort`=VALUES(`lowPort`), `highPort`=VALUES(`highPort`)'  
2018/08/21 12:00:39 - CMDPHP SQL Backtrace: (/plugins/mactrack/mactrack_device_types.php: 78 form_save)(/plugins/mactrack/mactrack_device_types.php: 128 api_mactrack_device_type_save)(/plugins/mactrack/mactrack_device_types.php: 176 sql_save)(/lib/database.php: 1002 _db_replace)(/lib/database.php: 949 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)  
2018/08/21 12:00:39 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'dot1x_scanning_function' in 'field list'  
2018/08/21 12:00:39 - DBCALL ERROR: A DB Exec Failed!, Error:1054, SQL:'INSERT INTO mac_track_device_types (`device_type_id`, `description`, `vendor`, `device_type`, `sysDescr_match`, `sysObjectID_match`, `serial_number_oid`, `scanning_function`, `ip_scanning_function`, `dot1x_scanning_function`, `lowPort`, `highPort`) VALUES (0, 'Nexus 5000', 'Cisco', '1', '', '', '', '0', '0', '0', 0, 0) ON DUPLICATE KEY UPDATE `description`=VALUES(`description`), `vendor`=VALUES(`vendor`), `device_type`=VALUES(`device_type`), `sysDescr_match`=VALUES(`sysDescr_match`), `sysObjectID_match`=VALUES(`sysObjectID_match`), `serial_number_oid`=VALUES(`serial_number_oid`), `scanning_function`=VALUES(`scanning_function`), `ip_scanning_function`=VALUES(`ip_scanning_function`), `dot1x_scanning_function`=VALUES(`dot1x_scanning_function`), `lowPort`=VALUES(`lowPort`), `highPort`=VALUES(`highPort`)'  
`

**Comment by netniV** [comment]
Please ensure you have the latest development version as I have just been clicked on each option on the left, no errors.

**Comment by jdcoats** [comment]
2018/10/01 11:44:40 - SYSTEM STATS: Time:39.0228 Method:spine Processes:1 Threads:50 Hosts:1776 HostsPerProcess:1776 DataSources:83880 RRDsProcessed:0  
2018/10/01 11:44:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_device_types.php: 109 mactrack_device_type)(/plugins/mactrack/mactrack_device_types.php: 958 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/10/01 11:44:35 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined index: dot1x_scanning_function in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_device_types.php on line: 958  
2018/10/01 11:44:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_device_types.php: 109 mactrack_device_type)(/plugins/mactrack/mactrack_device_types.php: 958 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/10/01 11:44:35 - ERROR PHP NOTICE in Plugin 'mactrack': Undefined index: dot1x_scanning_function in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_device_types.php on line: 958

**Comment by jdcoats** [comment]
This is what happens when I try to edit a device type.

2018/10/01 11:46:44 - DBCALL ERROR: SQL Save Failed for Table 'mac_track_device_types'. SQL:'INSERT INTO mac_track_device_types (`device_type_id`, `description`, `vendor`, `device_type`, `sysDescr_match`, `sysObjectID_match`, `serial_number_oid`, `scanning_function`, `ip_scanning_function`, `dot1x_scanning_function`, `lowPort`, `highPort`) VALUES (79, '94xx Switch', 'Cisco', '2', 'CAT9K_IOSXE', '', '', 'get_IOS_dot1dTpFdbEntry_ports', 'get_standard_arp_table', 'get_cisco_dot1x_table', 0, 0) ON DUPLICATE KEY UPDATE `description`=VALUES(`description`), `vendor`=VALUES(`vendor`), `device_type`=VALUES(`device_type`), `sysDescr_match`=VALUES(`sysDescr_match`), `sysObjectID_match`=VALUES(`sysObjectID_match`), `serial_number_oid`=VALUES(`serial_number_oid`), `scanning_function`=VALUES(`scanning_function`), `ip_scanning_function`=VALUES(`ip_scanning_function`), `dot1x_scanning_function`=VALUES(`dot1x_scanning_function`), `lowPort`=VALUES(`lowPort`), `highPort`=VALUES(`highPort`)'  
2018/10/01 11:46:44 - CMDPHP SQL Backtrace: (/plugins/mactrack/mactrack_device_types.php: 78 form_save)(/plugins/mactrack/mactrack_device_types.php: 128 api_mactrack_device_type_save)(/plugins/mactrack/mactrack_device_types.php: 176 sql_save)(/lib/database.php: 1002 _db_replace)(/lib/database.php: 949 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)  
2018/10/01 11:46:44 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'dot1x_scanning_function' in 'field list'  
2018/10/01 11:46:44 - DBCALL ERROR: A DB Exec Failed!, Error:1054, SQL:'INSERT INTO mac_track_device_types (`device_type_id`, `description`, `vendor`, `device_type`, `sysDescr_match`, `sysObjectID_match`, `serial_number_oid`, `scanning_function`, `ip_scanning_function`, `dot1x_scanning_function`, `lowPort`, `highPort`) VALUES (79, '94xx Switch', 'Cisco', '2', 'CAT9K_IOSXE', '', '', 'get_IOS_dot1dTpFdbEntry_ports', 'get_standard_arp_table', 'get_cisco_dot1x_table', 0, 0) ON DUPLICATE KEY UPDATE `description`=VALUES(`description`), `vendor`=VALUES(`vendor`), `device_type`=VALUES(`device_type`), `sysDescr_match`=VALUES(`sysDescr_match`), `sysObjectID_match`=VALUES(`sysObjectID_match`), `serial_number_oid`=VALUES(`serial_number_oid`), `scanning_function`=VALUES(`scanning_function`), `ip_scanning_function`=VALUES(`ip_scanning_function`), `dot1x_scanning_function`=VALUES(`dot1x_scanning_function`), `lowPort`=VALUES(`lowPort`), `highPort`=VALUES(`highPort`)'  
2018/10/01 11:46:44 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_device_types.php: 78 form_save)(/plugins/mactrack/mactrack_device_types.php: 128 api_mactrack_device_type_save)(/plugins/mactrack/mactrack_device_types.php: 176 sql_save)(/lib/database.php: 979 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/10/01 11:46:44 - ERROR PHP NOTICE: Undefined index: dot1x_scanning_function in file: /var/www/localhost/htdocs/cacti/lib/database.php on line: 979  
2018/10/01 11:46:44 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/mactrack_device_types.php: 78 form_save)(/plugins/mactrack/mactrack_device_types.php: 128 api_mactrack_device_type_save)(/plugins/mactrack/mactrack_device_types.php: 176 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/10/01 11:46:44 - ERROR PHP NOTICE: Undefined index: dot1x_scanning_function in file: /var/www/localhost/htdocs/cacti/lib/database.php on line: 978

**Comment by cigamit** [comment]
You are missing the dot1x column in the Device Types table.  Can you compare and manually add it?

**Comment by jdcoats** [comment]
im way past that close this and concentrate on #103. I uninstalled and reinstalled the plugin to get the table created correctly. It was my "device_types" restore that was breaking it. I added the column to my restore script :)

**Comment by jdcoats** [comment]
Thanks!

**Comment by cigamit** [comment]
Going to close this one.  But opening another to use the new table creation functions.
