### ISSUE TITLE
backtrace lib/database.php

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#91]
If I leave mactrack running for a while it will crash MySQL. I'm not sure what caused this, It was running fine for weeks and then not. I cant figure out what has changed, I'm not aware of anything.

> 2018/09/05 10:33:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/poller_mactrack.php: 117 clear_old_processes)(/plugins/mactrack/poller_mactrack.php: 387 db_execute_prepared)(/lib/database.php: 166 execute)(CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/09/05 10:33:03 - ERROR PHP NOTICE: Array to string conversion in file: /var/www/localhost/htdocs/cacti/lib/database.php on line: 166  
2018/09/05 10:33:03 - CMDPHP WARNING: Removing Hung Device Tracking Process for Device '328' With Status 'Running'  
2018/09/05 10:33:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/poller_mactrack.php: 117 clear_old_processes)(/plugins/mactrack/poller_mactrack.php: 387 db_execute_prepared)(/lib/database.php: 166 execute)(CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/09/05 10:33:03 - ERROR PHP NOTICE: Array to string conversion in file: /var/www/localhost/htdocs/cacti/lib/database.php on line: 166  
2018/09/05 10:33:03 - CMDPHP WARNING: Removing Hung Device Tracking Process for Device '319' With Status 'Running'  
2018/09/05 10:33:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/poller_mactrack.php: 117 clear_old_processes)(/plugins/mactrack/poller_mactrack.php: 387 db_execute_prepared)(/lib/database.php: 166 execute)(CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/09/05 10:33:03 - ERROR PHP NOTICE: Array to string conversion in file: /var/www/localhost/htdocs/cacti/lib/database.php on line: 166  
2018/09/05 10:33:03 - CMDPHP WARNING: Removing Hung Device Tracking Process for Device '317' With Status 'Running'  
2018/09/05 10:33:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/poller_mactrack.php: 117 clear_old_processes)(/plugins/mactrack/poller_mactrack.php: 387 db_execute_prepared)(/lib/database.php: 166 execute)(CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/09/05 10:33:03 - ERROR PHP NOTICE: Array to string conversion in file: /var/www/localhost/htdocs/cacti/lib/database.php on line: 166  
2018/09/05 10:33:03 - CMDPHP WARNING: Removing Hung Device Tracking Process for Device '308' With Status 'Running'  
2018/09/05 10:33:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/mactrack/poller_mactrack.php: 117 clear_old_processes)(/plugins/mactrack/poller_mactrack.php: 387 db_execute_prepared)(/lib/database.php: 166 execute)(CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)  
2018/09/05 10:33:03 - ERROR PHP NOTICE: Array to string conversion in file: /var/www/localhost/htdocs/cacti/lib/database.php on line: 166  
2018/09/05 10:33:03 - CMDPHP WARNING: Removing Hung Device Tracking Process for Device '304' With Status 'Running'  
>

**Comment by netniV** [comment]
What version of Cacti are you running?

**Comment by jdcoats** [comment]
1.1.38 and mactrack 4.2

**Comment by cigamit** [comment]
Wow, this has been out there that long.  Sorry, have not been paying attention to the plugins lately.
