### ISSUE TITLE
Cisco SB

### ISSUE THREAD

**Issue by beh0ld** [Cacti/plugin_mactrack#92]
Hi!
Mac Track and Cisco SB SG/SF works with "get_generic_switch_ports" only, but i have wrong port number in web output and didnt have vlan id, help me fix it, please. 

![image](https://user-images.githubusercontent.com/38158560/46332806-8ce9f580-c626-11e8-946d-e3917ef6e303.png)

**Comment by beh0ld** [comment]
It works with "get_generic_switch_ports", but i have wrong port number in web output, help me fix it, please.
![image](https://user-images.githubusercontent.com/38158560/46332806-8ce9f580-c626-11e8-946d-e3917ef6e303.png)

**Comment by jpobeda** [comment]
So `get_generic_switch_ports` actually calls `get_base_dot1dTpFdbEntry_ports` to populate most of those fields.

For the port number thing, try snmpwalk this 

```php
$port_numbers = xform_stripped_oid(".1.3.6.1.2.1.17.4.3.1.2", $device, $snmp_readstring);
```

On the other hand, you need to understand what are you after first

From [Wikipedia](https://en.wikipedia.org/wiki/IEEE_802.1D)

> Bridges using virtual LANs (VLANs) have never been part of 802.1D, but were instead specified in separate standard, 802.1Q originally published in 1998.

So if you're really interested on VLANs you should be using one of the Dot1Q functions like

Function `get_IOS_dot1dTpFdbEntry_ports` should really be called `get_IOS_dot1q...`

If you change your device type to match above MAC address scanning function and still doesn't work, 
try snmpwalk these OIDs

```php
$vlan_ids         = xform_standard_indexed_data(".1.3.6.1.4.1.9.9.46.1.3.1.1.2", $device);
$vlan_names       = xform_standard_indexed_data(".1.3.6.1.4.1.9.9.46.1.3.1.1.4", $device);
$vlan_trunkstatus = xform_standard_indexed_data(".1.3.6.1.4.1.9.9.46.1.6.1.1.14", $device);
```

I don't think this is a bug though, but @beh0ld provide feedback/update.

**Comment by netniV** [comment]
Did this work for you @beh0ld ?

**Comment by beh0ld** [comment]
> Did this work for you @beh0ld ?

Yes, thank you.
