### ISSUE TITLE
Cannot delete Mac Watch entries

### ISSUE THREAD

**Issue by chris-y** [Cacti/plugin_mactrack#96]
Attempting to delete an entry from Tracking Tools => Mac Watch results in the error "You must select at least one watched Mac to delete."

There are no checkboxes on the list (other than "select all") so the only option appears to be to highlight the rows.

Currently I can see no way of deleting items from this list.

Cacti 1.1.38
Macwatch plugin 4.2 (HEAD c34020731f2cfa62e8d89603a489f310ac68a148)

**Comment by netniV** [comment]
If non are showing checkboxes that would usually suggest the code believes you shouldn't be removing them.  As for the reason why, a dig into the code is required.  I think I opened a bug tracker for the no items but go works in the cacti core, but that is unlike to be addressed before 1.3 t the earliest.

**Comment by cigamit** [comment]
Resolved.
