### ISSUE TITLE
Counters don't decrease

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_mactrack#97]
Hi!
Since I use mactrack I've got the following problem:
my switchport does have output errors:
![grafik](https://user-images.githubusercontent.com/28043745/47998707-96bcb800-e100-11e8-9251-8b29e0e99f55.png)

It is shown correctly in mactrack:
![grafik](https://user-images.githubusercontent.com/28043745/47998502-d505a780-e0ff-11e8-832a-a25e38cf731e.png)

But the problem is when I clear the counters:
![grafik](https://user-images.githubusercontent.com/28043745/48060664-efea2180-e1bc-11e8-8d75-681e7399777e.png)

mactrack doesn't adjust that:
![grafik](https://user-images.githubusercontent.com/28043745/47998882-02068a00-e101-11e8-8873-e327076a4351.png)

As you can see in the picture the interface poller is up to date and running every 10 minutes.

The same behavoiur for input errros.
Am I the only one who got that problem? Can someone tell me how to fix that?
Thank you.
(cacti 1.2 beta2; mactrack 4.2)

**Comment by jpobeda** [comment]
Same thing here, never realized about it.

**Comment by cigamit** [comment]
Well, that's weird.  Well, normally I would say truncate the interface graphs.   What happens if you just delete that one row.  Do the errors come right back after the next scan?

**Comment by Axel577** [comment]
@cigamit What do you mean with 'delete that one row' ?

**Comment by cigamit** [comment]
From the mac_track_interfaces table

**Comment by cigamit** [comment]
Also, I think it may be complaining that the interface is taking errors.  Not sure, you did not provide the entire page.

**Comment by jdcoats** [comment]
Just to try to bump this into more recent visibility. If you have ports with errors and correct those errors and clear counters, the counters never reset or clear in mactrack. None of the provided mactrack utilities clean-up mac_track_interface_graphs or mac_track_interfaces. It seems that maybe even the extreme "remove all scan results" should also truncate those 2 tables since it does say "start all over" :) There may be a more graceful way to handle the counters but this would be a quick and easy from the gui rather than someone having to:
```
MariaDB [cacti]> truncate mac_track_interface_graphs;
Query OK, 0 rows affected (0.026 sec)

MariaDB [cacti]> truncate mac_track_interfaces;
Query OK, 0 rows affected (0.039 sec)

```

**Comment by TheWitness** [comment]
Yea, that's a bit extreme.  I don't want to bury myself in mactrack at the moment, but seems there are a bunch of little bugs.  It could use some love.

**Comment by TheWitness** [comment]
I took a look at the code, and I think when I wrote this thing, I though that counters would count down instead of up.  What they do really is simply overflow and start back at zero.  If someone can confirm that, then this bug will be easy to fix.

**Comment by TheWitness** [comment]
@jdcoats & @Axel577, the last comment was for your two.
