### ISSUE TITLE
Auto database maintenance does not run

### ISSUE THREAD

**Issue by chris-y** [Cacti/plugin_mactrack#98]
This is an old issue, see https://forums.cacti.net/viewtopic.php?f=15&t=12537

Database maintenance does not appear to run on a schedule as it is supposed to.  The fix given in that thread works but has an issue (also theoretically present in the existing code) that adding 24 hours to the last maintenance time does not guarantee that it will run at the set time set and is liable to drift.

The existing code fails because it checks against the current time and when now<db_maint_time the clock gets set one hour ahead so the second check of now<db_maint_time never runs.

This probably needs re-writing so it always runs at db_maint_time and then advances the next_db_maint_time to the following day after it has run.

**Comment by netniV** [comment]
This has now been committed to the development code.
